# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class BlogBlog(models.Model):
    sequence: Any
    name: Any
    subtitle: Any
    active: Any
    content: Any
    blog_post_ids: Any
    blog_post_count: Any
    def _default_sequence(self: Any) -> Any: ...
    def _compute_blog_post_count(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def message_post(self: Any, *, parent_id: Any = ..., subtype_id: Any = ..., **kwargs: Any) -> Any: ...
    def all_tags(self: Any, join: Any = ..., min_limit: Any = ...) -> Any: ...
    def _search_get_detail(self: Any, website: Any, order: Any, options: Any) -> Any: ...
    def _search_render_results(self: Any, fetch_fields: Any, mapping: Any, icon: Any, limit: Any) -> Any: ...

class BlogPost(models.Model):
    name: Any
    subtitle: Any
    author_id: Any
    author_avatar: Any
    author_name: Any
    active: Any
    blog_id: Any
    tag_ids: Any
    content: Any
    teaser: Any
    teaser_manual: Any
    website_message_ids: Any
    create_date: Any
    published_date: Any
    post_date: Any
    create_uid: Any
    write_date: Any
    write_uid: Any
    visits: Any
    website_id: Any
    def _compute_website_url(self: Any) -> Any: ...
    def _default_content(self: Any) -> Any: ...
    def _compute_teaser(self: Any) -> Any: ...
    def _set_teaser(self: Any) -> Any: ...
    def _compute_post_date(self: Any) -> Any: ...
    def _set_post_date(self: Any) -> Any: ...
    def _check_for_publication(self: Any, vals: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def copy_data(self: Any, default: Any = ...) -> Any: ...
    def _get_access_action(self: Any, access_uid: Any = ..., force_website: Any = ...) -> Any: ...
    def _notify_get_recipients_groups(self: Any, message: Any, model_description: Any, msg_vals: Any = ...) -> Any: ...
    def _notify_thread_by_inbox(self: Any, message: Any, recipients_data: Any, msg_vals: Any = ..., **kwargs: Any) -> Any: ...
    def _default_website_meta(self: Any) -> Any: ...
    def _search_get_detail(self: Any, website: Any, order: Any, options: Any) -> Any: ...

class BlogTag(models.Model):
    name: Any
    category_id: Any
    color: Any
    post_ids: Any

class BlogTagCategory(models.Model):
    name: Any
    tag_ids: Any

