# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResPartner(models.Model):
    meeting_count: Any
    meeting_ids: Any
    calendar_last_notif_ack: Any
    def _compute_application_statistics_hook(self: Any) -> Any: ...
    def _compute_meeting_count(self: Any) -> Any: ...
    def _compute_meeting(self: Any) -> Any: ...
    def get_attendee_detail(self: Any, meeting_ids: Any) -> Any: ...
    def _creation_message(self: Any) -> Any: ...
    def _set_calendar_last_notif_ack(self: Any) -> Any: ...
    def schedule_meeting(self: Any) -> Any: ...
    def _get_busy_calendar_events(self: Any, start_datetime: Any, end_datetime: Any) -> Any: ...

