# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PaymentToken(models.Model):
    provider_id: Any
    provider_code: Any
    company_id: Any
    payment_method_id: Any
    payment_method_code: Any
    payment_details: Any
    partner_id: Any
    provider_ref: Any
    transaction_ids: Any
    active: Any
    def _compute_display_name(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def _get_specific_create_values(self: Any, provider_code: Any, values: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _check_partner_is_never_public(self: Any) -> Any: ...
    def _handle_archiving(self: Any) -> Any: ...
    def _get_available_tokens(self: Any, providers_ids: Any, partner_id: Any, is_validation: Any = ..., **kwargs: Any) -> Any: ...
    def _build_display_name(self: Any, *args: Any, max_length: Any = ..., should_pad: Any = ..., **kwargs: Any) -> Any: ...
    def get_linked_records_info(self: Any) -> Any: ...

