# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PaymentMethod(models.Model):
    name: Any
    code: Any
    sequence: Any
    primary_payment_method_id: Any
    brand_ids: Any
    is_primary: Any
    provider_ids: Any
    active: Any
    image: Any
    image_payment_form: Any
    support_tokenization: Any
    support_express_checkout: Any
    support_manual_capture: Any
    support_refund: Any
    supported_country_ids: Any
    supported_currency_ids: Any
    def _compute_is_primary(self: Any) -> Any: ...
    def _search_is_primary(self: Any, operator: Any, value: Any) -> Any: ...
    def _onchange_warn_before_disabling_tokens(self: Any) -> Any: ...
    def _onchange_provider_ids_warn_before_attaching_payment_method(self: Any) -> Any: ...
    def _check_manual_capture_supported_by_providers(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _unlink_if_not_default_payment_method(self: Any) -> Any: ...
    def _get_compatible_payment_methods(self: Any, provider_ids: Any, partner_id: Any, currency_id: Any = ..., force_tokenization: Any = ..., is_express_checkout: Any = ..., report: Any = ..., **kwargs: Any) -> Any: ...
    def _get_from_code(self: Any, code: Any, mapping: Any = ...) -> Any: ...

