# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    group_use_lead: Any
    group_use_recurring_revenues: Any
    is_membership_multi: Any
    module_partnership: Any
    crm_use_auto_assignment: Any
    crm_auto_assignment_action: Any
    crm_auto_assignment_interval_type: Any
    crm_auto_assignment_interval_number: Any
    crm_auto_assignment_run_datetime: Any
    module_crm_iap_mine: Any
    module_crm_iap_enrich: Any
    module_website_crm_iap_reveal: Any
    lead_enrich_auto: Any
    lead_mining_in_pipeline: Any
    predictive_lead_scoring_start_date: Any
    predictive_lead_scoring_start_date_str: Any
    predictive_lead_scoring_fields: Any
    predictive_lead_scoring_fields_str: Any
    predictive_lead_scoring_field_labels: Any
    def set_values(self: Any) -> Any: ...
    def _compute_crm_auto_assignment_data(self: Any) -> Any: ...
    def _onchange_crm_auto_assignment_run_datetime(self: Any) -> Any: ...
    def _compute_pls_fields(self: Any) -> Any: ...
    def _inverse_pls_fields_str(self: Any) -> Any: ...
    def _compute_pls_start_date(self: Any) -> Any: ...
    def _inverse_pls_start_date_str(self: Any) -> Any: ...
    def _compute_predictive_lead_scoring_field_labels(self: Any) -> Any: ...
    def _get_crm_auto_assignmment_run_datetime(self: Any, run_datetime: Any, run_interval: Any, run_interval_number: Any) -> Any: ...
    def action_crm_assign_leads(self: Any) -> Any: ...

