# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailMessage(models.Model):
    def _compute_is_current_user_or_guest_author(self: Any) -> Any: ...
    def portal_message_format(self: Any, options: Any = ...) -> Any: ...
    def _portal_get_default_format_properties_names(self: Any, options: Any = ...) -> Any: ...
    def _portal_message_format(self: Any, properties_names: Any, options: Any = ...) -> Any: ...
    def _portal_message_format_attachments(self: Any, attachment_values: Any) -> Any: ...

