# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PortalMixin(models.AbstractModel):
    access_url: Any
    access_token: Any
    access_warning: Any
    def _compute_access_warning(self: Any) -> Any: ...
    def _compute_access_url(self: Any) -> Any: ...
    def _portal_ensure_token(self: Any) -> Any: ...
    def _get_share_url(self: Any, redirect: Any = ..., signup_partner: Any = ..., pid: Any = ..., share_token: Any = ...) -> Any: ...
    def _get_access_action(self: Any, access_uid: Any = ..., force_website: Any = ...) -> Any: ...
    def action_share(self: Any) -> Any: ...
    def get_portal_url(self: Any, suffix: Any = ..., report_type: Any = ..., download: Any = ..., query_string: Any = ..., anchor: Any = ...) -> Any: ...

