# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PortalShare(models.TransientModel):
    res_model: Any
    res_id: Any
    resource_ref: Any
    partner_ids: Any
    note: Any
    share_link: Any
    access_warning: Any
    def default_get(self: Any, fields: Any) -> Any: ...
    def _selection_target_model(self: Any) -> Any: ...
    def _compute_resource_ref(self: Any) -> Any: ...
    def _compute_share_link(self: Any) -> Any: ...
    def _compute_access_warning(self: Any) -> Any: ...
    def _send_public_link(self: Any, partners: Any = ...) -> Any: ...
    def _send_signup_link(self: Any, partners: Any = ...) -> Any: ...
    def action_send_mail(self: Any) -> Any: ...

