# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    company_id: Any
    is_root_company: Any
    module_base_import: Any
    module_google_calendar: Any
    module_microsoft_calendar: Any
    module_mail_plugin: Any
    module_auth_oauth: Any
    module_auth_ldap: Any
    module_account_inter_company_rules: Any
    module_voip: Any
    module_web_unsplash: Any
    module_sms: Any
    module_partner_autocomplete: Any
    module_base_geolocalize: Any
    module_google_recaptcha: Any
    module_website_cf_turnstile: Any
    module_google_address_autocomplete: Any
    report_footer: Any
    group_multi_currency: Any
    external_report_layout_id: Any
    show_effect: Any
    company_count: Any
    active_user_count: Any
    language_count: Any
    company_name: Any
    company_informations: Any
    company_country_code: Any
    company_country_group_codes: Any
    profiling_enabled_until: Any
    def open_company(self: Any) -> Any: ...
    def open_new_user_default_groups(self: Any) -> Any: ...
    def _prepare_report_view_action(self: Any, template: Any) -> Any: ...
    def edit_external_header(self: Any) -> Any: ...
    def _compute_company_count(self: Any) -> Any: ...
    def _compute_active_user_count(self: Any) -> Any: ...
    def _compute_language_count(self: Any) -> Any: ...
    def _compute_company_informations(self: Any) -> Any: ...
    def _compute_is_root_company(self: Any) -> Any: ...

