# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class UpdateProductAttributeValue(models.TransientModel):
    attribute_value_id: Any
    mode: Any
    message: Any
    product_count: Any
    def _compute_message(self: Any) -> Any: ...
    def _compute_product_count(self: Any) -> Any: ...
    def action_confirm(self: Any) -> Any: ...
    def _add_value_to_existing_attribute_lines(self: Any) -> Any: ...
    def _update_extra_price_on_existing_products(self: Any) -> Any: ...

