# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResourceCalendarAttendance(models.Model):
    name: Any
    dayofweek: Any
    hour_from: Any
    hour_to: Any
    duration_hours: Any
    duration_days: Any
    calendar_id: Any
    duration_based: Any
    day_period: Any
    week_type: Any
    two_weeks_calendar: Any
    display_type: Any
    sequence: Any
    def _onchange_hours(self: Any) -> Any: ...
    def _check_day_period(self: Any) -> Any: ...
    def get_week_type(self: Any, date: Any) -> Any: ...
    def _compute_duration_hours(self: Any) -> Any: ...
    def _inverse_duration_hours(self: Any) -> Any: ...
    def _compute_duration_days(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def _copy_attendance_vals(self: Any) -> Any: ...
    def _is_work_period(self: Any) -> Any: ...

