# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PaymentCaptureWizard(models.TransientModel):
    transaction_ids: Any
    authorized_amount: Any
    captured_amount: Any
    voided_amount: Any
    available_amount: Any
    amount_to_capture: Any
    is_amount_to_capture_valid: Any
    void_remaining_amount: Any
    currency_id: Any
    support_partial_capture: Any
    has_draft_children: Any
    has_remaining_amount: Any
    def _compute_authorized_amount(self: Any) -> Any: ...
    def _compute_captured_amount(self: Any) -> Any: ...
    def _compute_voided_amount(self: Any) -> Any: ...
    def _compute_available_amount(self: Any) -> Any: ...
    def _compute_amount_to_capture(self: Any) -> Any: ...
    def _compute_is_amount_to_capture_valid(self: Any) -> Any: ...
    def _compute_support_partial_capture(self: Any) -> Any: ...
    def _compute_has_draft_children(self: Any) -> Any: ...
    def _compute_has_remaining_amount(self: Any) -> Any: ...
    def _check_amount_to_capture_within_boundaries(self: Any) -> Any: ...
    def action_capture(self: Any) -> Any: ...

