# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class BaseDocumentLayout(models.TransientModel):
    vat: Any
    company_id: Any
    logo: Any
    preview_logo: Any
    report_header: Any
    report_footer: Any
    company_details: Any
    is_company_details_empty: Any
    paperformat_id: Any
    external_report_layout_id: Any
    font: Any
    primary_color: Any
    secondary_color: Any
    custom_colors: Any
    logo_primary_color: Any
    logo_secondary_color: Any
    layout_background: Any
    layout_background_image: Any
    report_layout_id: Any
    preview: Any
    partner_id: Any
    phone: Any
    email: Any
    website: Any
    name: Any
    country_id: Any
    def document_layout_save(self: Any) -> Any: ...
    def _get_preview_template(self: Any) -> Any: ...
    def _get_render_information(self: Any, styles: Any) -> Any: ...
    def _compute_preview(self: Any) -> Any: ...
    def _default_report_footer(self: Any) -> Any: ...
    def _default_company_details(self: Any) -> Any: ...
    def _clean_address_format(self: Any, address_format: Any, company_data: Any) -> Any: ...
    def _compute_custom_colors(self: Any) -> Any: ...
    def _compute_logo_colors(self: Any) -> Any: ...
    def _onchange_company_id(self: Any) -> Any: ...
    def _onchange_custom_colors(self: Any) -> Any: ...
    def _onchange_report_layout_id(self: Any) -> Any: ...
    def _onchange_logo(self: Any) -> Any: ...
    def extract_image_primary_secondary_colors(self: Any, logo: Any, white_threshold: Any = ..., mitigate: Any = ...) -> Any: ...
    def _get_asset_style(self: Any) -> Any: ...
    def _get_css_for_preview(self: Any, scss: Any, new_id: Any) -> Any: ...
    def _compute_empty_company_details(self: Any) -> Any: ...

