# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountAnalyticLine(models.Model):
    product_id: Any
    product_category: Any
    general_account_id: Any
    journal_id: Any
    partner_id: Any
    move_line_id: Any
    code: Any
    ref: Any
    category: Any
    analytic_profitability: Any
    def _compute_general_account_id(self: Any) -> Any: ...
    def _check_general_account_id(self: Any) -> Any: ...
    def _compute_partner_id(self: Any) -> Any: ...
    def _compute_analytic_profitability(self: Any) -> Any: ...
    def on_change_unit_amount(self: Any) -> Any: ...
    def view_header_get(self: Any, view_id: Any, view_type: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def _field_to_sql(self: Any, alias: Any, field_expr: Any, query: Any = ...) -> Any: ...
    def _search_analytic_profitability(self: Any, operator: Any, value: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...

