# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountAccountTag(models.Model):
    name: Any
    applicability: Any
    color: Any
    active: Any
    country_id: Any
    report_expression_id: Any
    balance_negate: Any
    def _compute_display_name(self: Any) -> Any: ...
    def _compute_report_expression_id(self: Any) -> Any: ...
    def _field_to_sql(self: Any, alias: Any, field_expr: Any, query: Any = ...) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def _get_tax_tags(self: Any, tag_name: Any, country_id: Any) -> Any: ...
    def _get_tax_tags_domain(self: Any, formula: Any, country_id: Any) -> Any: ...
    def _get_related_tax_report_expressions(self: Any) -> Any: ...
    def _unlink_except_master_tags(self: Any) -> Any: ...
    def _translate_tax_tags(self: Any, langs: Any = ..., tag_ids: Any = ...) -> Any: ...

