# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountAnalyticDistributionModel(models.Model):
    account_prefix: Any
    product_id: Any
    product_categ_id: Any
    prefix_placeholder: Any
    def _get_default_search_domain_vals(self: Any) -> Any: ...
    def _get_applicable_models(self: Any, vals: Any) -> Any: ...
    def _create_domain(self: Any, fname: Any, value: Any) -> Any: ...
    def _compute_prefix_placeholder(self: Any) -> Any: ...

