# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountPaymentMethod(models.Model):
    name: Any
    code: Any
    payment_type: Any
    def create(self: Any, vals_list: Any) -> Any: ...
    def _auto_link_payment_methods(self: Any, payment_methods: Any, methods_info: Any) -> Any: ...
    def _get_payment_method_domain(self: Any, code: Any, with_currency: Any = ..., with_country: Any = ...) -> Any: ...
    def _get_payment_method_information(self: Any) -> Any: ...
    def _get_sdd_payment_method_code(self: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...

class AccountPaymentMethodLine(models.Model):
    name: Any
    sequence: Any
    payment_method_id: Any
    payment_account_id: Any
    journal_id: Any
    default_account_id: Any
    code: Any
    payment_type: Any
    company_id: Any
    available_payment_method_ids: Any
    def _compute_display_name(self: Any) -> Any: ...
    def _compute_name(self: Any) -> Any: ...
    def _ensure_unique_name_for_journal(self: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def _auto_toggle_account_to_reconcile(self: Any, account_id: Any) -> Any: ...

