# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountReconcileModel(models.Model):
    active: Any
    name: Any
    sequence: Any
    company_id: Any
    trigger: Any
    next_activity_type_id: Any
    can_be_proposed: Any
    mapped_partner_id: Any
    match_journal_ids: Any
    match_amount: Any
    match_amount_min: Any
    match_amount_max: Any
    match_label: Any
    match_label_param: Any
    match_partner_ids: Any
    line_ids: Any
    def _check_match_label_param(self: Any) -> Any: ...
    def _compute_can_be_proposed(self: Any) -> Any: ...
    def _compute_partner_mapping(self: Any) -> Any: ...
    def action_set_manual(self: Any) -> Any: ...
    def action_set_auto_reconcile(self: Any) -> Any: ...
    def action_reconcile_stat(self: Any) -> Any: ...
    def copy_data(self: Any, default: Any = ...) -> Any: ...

class AccountReconcileModelLine(models.Model):
    model_id: Any
    company_id: Any
    sequence: Any
    account_id: Any
    partner_id: Any
    label: Any
    amount_type: Any
    amount: Any
    amount_string: Any
    tax_ids: Any
    def _onchange_amount_type(self: Any) -> Any: ...
    def _compute_float_amount(self: Any) -> Any: ...
    def _validate_amount(self: Any) -> Any: ...

