# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountReport(models.Model):
    name: Any
    sequence: Any
    active: Any
    line_ids: Any
    column_ids: Any
    root_report_id: Any
    variant_report_ids: Any
    section_report_ids: Any
    section_main_report_ids: Any
    use_sections: Any
    chart_template: Any
    country_id: Any
    only_tax_exigible: Any
    availability_condition: Any
    load_more_limit: Any
    search_bar: Any
    prefix_groups_threshold: Any
    integer_rounding: Any
    allow_foreign_vat: Any
    default_opening_date_filter: Any
    currency_translation: Any
    filter_multi_company: Any
    filter_date_range: Any
    filter_show_draft: Any
    filter_unreconciled: Any
    filter_unfold_all: Any
    filter_hide_0_lines: Any
    filter_period_comparison: Any
    filter_growth_comparison: Any
    filter_journals: Any
    filter_analytic: Any
    filter_hierarchy: Any
    filter_account_type: Any
    filter_partner: Any
    filter_aml_ir_filters: Any
    filter_budgets: Any
    def _compute_report_option_filter(self: Any, field_name: Any, default_value: Any = ...) -> Any: ...
    def _compute_default_availability_condition(self: Any) -> Any: ...
    def _compute_use_sections(self: Any) -> Any: ...
    def _validate_root_report_id(self: Any) -> Any: ...
    def _validate_parent_sequence(self: Any) -> Any: ...
    def _validate_section_report_ids(self: Any) -> Any: ...
    def _validate_availability_condition(self: Any) -> Any: ...
    def _onchange_availability_condition(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def copy_data(self: Any, default: Any = ...) -> Any: ...
    def copy(self: Any, default: Any = ...) -> Any: ...
    def _unlink_if_no_variant(self: Any) -> Any: ...
    def _get_copied_name(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...

class AccountReportColumn(models.Model):
    name: Any
    expression_label: Any
    sequence: Any
    report_id: Any
    sortable: Any
    figure_type: Any
    blank_if_zero: Any
    custom_audit_action_id: Any

class AccountReportExpression(models.Model):
    report_line_id: Any
    report_line_name: Any
    label: Any
    engine: Any
    formula: Any
    subformula: Any
    date_scope: Any
    figure_type: Any
    green_on_positive: Any
    blank_if_zero: Any
    auditable: Any
    carryover_target: Any
    def _check_carryover_target(self: Any) -> Any: ...
    def _check_formula(self: Any) -> Any: ...
    def _compute_auditable(self: Any) -> Any: ...
    def _validate_engine(self: Any) -> Any: ...
    def _get_auditable_engines(self: Any) -> Any: ...
    def _strip_formula(self: Any, vals: Any) -> Any: ...
    def _create_tax_tags(self: Any, tag_name: Any, country: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _unlink_archive_used_tags(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def _expand_aggregations(self: Any) -> Any: ...
    def _get_aggregation_terms_details(self: Any) -> Any: ...
    def _get_matching_tags(self: Any) -> Any: ...
    def _get_tags_create_vals(self: Any, tag_name: Any, country_id: Any, existing_tag: Any = ...) -> Any: ...
    def _get_carryover_target_expression(self: Any, options: Any) -> Any: ...

class AccountReportExternalValue(models.Model):
    name: Any
    value: Any
    text_value: Any
    date: Any
    target_report_expression_id: Any
    target_report_line_id: Any
    target_report_expression_label: Any
    report_country_id: Any
    company_id: Any
    carryover_origin_expression_label: Any
    carryover_origin_report_line_id: Any

class AccountReportLine(models.Model):
    name: Any
    expression_ids: Any
    report_id: Any
    hierarchy_level: Any
    parent_id: Any
    children_ids: Any
    groupby: Any
    user_groupby: Any
    sequence: Any
    code: Any
    foldable: Any
    print_on_new_page: Any
    action_id: Any
    hide_if_zero: Any
    domain_formula: Any
    account_codes_formula: Any
    aggregation_formula: Any
    external_formula: Any
    horizontal_split_side: Any
    tax_tags_formula: Any
    def _compute_hierarchy_level(self: Any) -> Any: ...
    def _compute_report_id(self: Any) -> Any: ...
    def _compute_horizontal_split_side(self: Any) -> Any: ...
    def _compute_user_groupby(self: Any) -> Any: ...
    def _validate_groupby_no_child(self: Any) -> Any: ...
    def _validate_groupby(self: Any) -> Any: ...
    def _check_parent_line(self: Any) -> Any: ...
    def _copy_hierarchy(self: Any, copied_report: Any, parent: Any = ..., code_mapping: Any = ...) -> Any: ...
    def _get_copied_code(self: Any) -> Any: ...
    def _inverse_domain_formula(self: Any) -> Any: ...
    def _inverse_aggregation_formula(self: Any) -> Any: ...
    def _inverse_aggregation_tax_formula(self: Any) -> Any: ...
    def _inverse_account_codes_formula(self: Any) -> Any: ...
    def _inverse_external_formula(self: Any) -> Any: ...
    def _create_report_expression(self: Any, engine: Any) -> Any: ...
    def _unlink_child_expressions(self: Any) -> Any: ...

