# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    has_accounting_entries: Any
    currency_id: Any
    currency_exchange_journal_id: Any
    income_currency_exchange_account_id: Any
    expense_currency_exchange_account_id: Any
    has_chart_of_accounts: Any
    chart_template: Any
    sale_tax_id: Any
    purchase_tax_id: Any
    account_price_include: Any
    tax_calculation_rounding_method: Any
    account_journal_suspense_account_id: Any
    transfer_account_id: Any
    module_account_accountant: Any
    group_cash_rounding: Any
    show_sale_receipts: Any
    module_account_budget: Any
    module_account_payment: Any
    module_account_reports: Any
    module_account_check_printing: Any
    module_account_batch_payment: Any
    module_account_iso20022: Any
    module_account_sepa_direct_debit: Any
    module_account_bank_statement_import_qif: Any
    module_currency_rate_live: Any
    module_account_intrastat: Any
    module_product_margin: Any
    module_account_extract: Any
    module_account_invoice_extract: Any
    module_account_bank_statement_extract: Any
    module_snailmail_account: Any
    module_account_peppol: Any
    tax_exigibility: Any
    tax_cash_basis_journal_id: Any
    account_cash_basis_base_account_id: Any
    account_fiscal_country_id: Any
    qr_code: Any
    link_qr_code: Any
    incoterm_id: Any
    invoice_terms: Any
    invoice_terms_html: Any
    terms_type: Any
    display_invoice_amount_total_words: Any
    display_invoice_tax_company_currency: Any
    preview_ready: Any
    use_invoice_terms: Any
    account_use_credit_limit: Any
    account_default_credit_limit: Any
    country_code: Any
    account_storno: Any
    display_account_storno: Any
    group_sale_delivery_address: Any
    quick_edit_mode: Any
    account_journal_early_pay_discount_loss_account_id: Any
    account_journal_early_pay_discount_gain_account_id: Any
    account_discount_income_allocation_id: Any
    account_discount_expense_allocation_id: Any
    is_account_peppol_eligible: Any
    restrictive_audit_trail: Any
    force_restrictive_audit_trail: Any
    autopost_bills: Any
    income_account_id: Any
    expense_account_id: Any
    def _compute_is_account_peppol_eligible(self: Any) -> Any: ...
    def set_values(self: Any) -> Any: ...
    def reload_template(self: Any) -> Any: ...
    def _compute_account_default_credit_limit(self: Any) -> Any: ...
    def _inverse_account_default_credit_limit(self: Any) -> Any: ...
    def _compute_has_chart_of_accounts(self: Any) -> Any: ...
    def _compute_module_account_invoice_extract(self: Any) -> Any: ...
    def _compute_module_account_bank_statement_extract(self: Any) -> Any: ...
    def onchange_analytic_accounting(self: Any) -> Any: ...
    def onchange_module_account_budget(self: Any) -> Any: ...
    def _onchange_tax_exigibility(self: Any) -> Any: ...
    def _compute_terms_preview(self: Any) -> Any: ...
    def action_update_terms(self: Any) -> Any: ...
    def action_eu_oss_tax_mapping(self: Any) -> Any: ...

