# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ForumForum(models.Model):
    name: Any
    sequence: Any
    mode: Any
    privacy: Any
    authorized_group_id: Any
    active: Any
    faq: Any
    description: Any
    welcome_message: Any
    default_order: Any
    relevancy_post_vote: Any
    relevancy_time_decay: Any
    allow_share: Any
    post_ids: Any
    last_post_id: Any
    total_posts: Any
    total_views: Any
    total_answers: Any
    total_favorites: Any
    count_posts_waiting_validation: Any
    count_flagged_posts: Any
    karma_gen_question_new: Any
    karma_gen_question_upvote: Any
    karma_gen_question_downvote: Any
    karma_gen_answer_upvote: Any
    karma_gen_answer_downvote: Any
    karma_gen_answer_accept: Any
    karma_gen_answer_accepted: Any
    karma_gen_answer_flagged: Any
    karma_ask: Any
    karma_answer: Any
    karma_edit_own: Any
    karma_edit_all: Any
    karma_edit_retag: Any
    karma_close_own: Any
    karma_close_all: Any
    karma_unlink_own: Any
    karma_unlink_all: Any
    karma_tag_create: Any
    karma_upvote: Any
    karma_downvote: Any
    karma_answer_accept_own: Any
    karma_answer_accept_all: Any
    karma_comment_own: Any
    karma_comment_all: Any
    karma_comment_convert_own: Any
    karma_comment_convert_all: Any
    karma_comment_unlink_own: Any
    karma_comment_unlink_all: Any
    karma_flag: Any
    karma_dofollow: Any
    karma_editor: Any
    karma_user_bio: Any
    karma_post: Any
    karma_moderate: Any
    has_pending_post: Any
    can_moderate: Any
    tag_ids: Any
    tag_most_used_ids: Any
    tag_unused_ids: Any
    def _get_default_welcome_message(self: Any) -> Any: ...
    def _compute_has_pending_post(self: Any) -> Any: ...
    def _compute_can_moderate(self: Any) -> Any: ...
    def _compute_tag_ids_usage(self: Any) -> Any: ...
    def _compute_last_post_id(self: Any) -> Any: ...
    def _compute_forum_statistics(self: Any) -> Any: ...
    def _compute_count_posts_waiting_validation(self: Any) -> Any: ...
    def _compute_count_flagged_posts(self: Any) -> Any: ...
    def _compute_website_url(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _set_default_faq(self: Any) -> Any: ...
    def _tag_to_write_vals(self: Any, tags: Any = ...) -> Any: ...
    def _get_tags_first_char(self: Any, tags: Any = ...) -> Any: ...
    def go_to_website(self: Any) -> Any: ...
    def _search_get_detail(self: Any, website: Any, order: Any, options: Any) -> Any: ...
    def _search_render_results(self: Any, fetch_fields: Any, mapping: Any, icon: Any, limit: Any) -> Any: ...

