# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountAnalyticAccount(models.Model):
    name: Any
    code: Any
    active: Any
    plan_id: Any
    root_plan_id: Any
    color: Any
    line_ids: Any
    company_id: Any
    partner_id: Any
    balance: Any
    debit: Any
    credit: Any
    currency_id: Any
    def _check_company_consistency(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def copy_data(self: Any, default: Any = ...) -> Any: ...
    def web_read(self: Any, specification: Any) -> Any: ...
    def _read_group_select(self: Any, aggregate_spec: Any, query: Any) -> Any: ...
    def _read_group_postprocess_aggregate(self: Any, aggregate_spec: Any, raw_values: Any) -> Any: ...
    def _compute_debit_credit_balance(self: Any) -> Any: ...
    def _update_accounts_in_analytic_lines(self: Any, new_fname: Any, current_fname: Any, accounts: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...

