# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class GamificationBadge(models.Model):
    name: Any
    active: Any
    description: Any
    level: Any
    rule_auth: Any
    rule_auth_user_ids: Any
    rule_auth_badge_ids: Any
    rule_max: Any
    rule_max_number: Any
    challenge_ids: Any
    goal_definition_ids: Any
    owner_ids: Any
    granted_count: Any
    granted_users_count: Any
    unique_owner_ids: Any
    stat_this_month: Any
    stat_my: Any
    stat_my_this_month: Any
    stat_my_monthly_sending: Any
    remaining_sending: Any
    def _get_owners_info(self: Any) -> Any: ...
    def _get_badge_user_stats(self: Any) -> Any: ...
    def _remaining_sending_calc(self: Any) -> Any: ...
    def check_granting(self: Any) -> Any: ...
    def _can_grant_badge(self: Any) -> Any: ...

