# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class GamificationGoal(models.Model):
    definition_id: Any
    user_id: Any
    user_partner_id: Any
    line_id: Any
    challenge_id: Any
    start_date: Any
    end_date: Any
    target_goal: Any
    current: Any
    completeness: Any
    state: Any
    to_update: Any
    closed: Any
    computation_mode: Any
    color: Any
    remind_update_delay: Any
    last_update: Any
    definition_description: Any
    definition_condition: Any
    definition_suffix: Any
    definition_display: Any
    def _compute_color(self: Any) -> Any: ...
    def _get_completion(self: Any) -> Any: ...
    def _check_remind_delay(self: Any) -> Any: ...
    def _get_write_values(self: Any, new_value: Any) -> Any: ...
    def update_goal(self: Any) -> Any: ...
    def action_start(self: Any) -> Any: ...
    def action_reach(self: Any) -> Any: ...
    def action_fail(self: Any) -> Any: ...
    def action_cancel(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def get_action(self: Any) -> Any: ...
    def _mail_get_partner_fields(self: Any, introspect_fields: Any = ...) -> Any: ...

