# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class GamificationGoalDefinition(models.Model):
    name: Any
    description: Any
    monetary: Any
    suffix: Any
    full_suffix: Any
    computation_mode: Any
    display_mode: Any
    model_id: Any
    model_inherited_ids: Any
    field_id: Any
    field_date_id: Any
    domain: Any
    batch_mode: Any
    batch_distinctive_field: Any
    batch_user_expression: Any
    compute_code: Any
    condition: Any
    action_id: Any
    res_id_field: Any
    def _compute_full_suffix(self: Any) -> Any: ...
    def _check_domain_validity(self: Any) -> Any: ...
    def _check_model_validity(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...

