# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountInvoiceReport(models.Model):
    move_id: Any
    journal_id: Any
    company_id: Any
    company_currency_id: Any
    partner_id: Any
    commercial_partner_id: Any
    country_id: Any
    invoice_user_id: Any
    move_type: Any
    state: Any
    payment_state: Any
    fiscal_position_id: Any
    invoice_date: Any
    quantity: Any
    product_id: Any
    product_uom_id: Any
    product_categ_id: Any
    invoice_date_due: Any
    account_id: Any
    price_subtotal_currency: Any
    price_subtotal: Any
    price_total: Any
    price_total_currency: Any
    price_average: Any
    price_margin: Any
    inventory_value: Any
    currency_id: Any
    def _table_query(self: Any) -> Any: ...
    def _select(self: Any) -> Any: ...
    def _from(self: Any) -> Any: ...
    def _where(self: Any) -> Any: ...
    def _read_group_select(self: Any, aggregate_spec: Any, query: Any) -> Any: ...

class ReportAccountReport_Invoice(models.AbstractModel):
    def _get_report_values(self: Any, docids: Any, data: Any = ...) -> Any: ...

class ReportAccountReport_Invoice_With_Payments(models.AbstractModel):
    def _get_report_values(self: Any, docids: Any, data: Any = ...) -> Any: ...

