# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrActionsServer(models.Model):
    xml_id: Any
    website_path: Any
    website_url: Any
    website_published: Any
    def _run_action_code_multi(self: Any, eval_context: Any = ...) -> Any: ...
    def _get_eval_context(self: Any, action: Any) -> Any: ...
    def _compute_xml_id(self: Any) -> Any: ...
    def _compute_website_url(self: Any, website_path: Any, xml_id: Any) -> Any: ...
    def _get_website_url(self: Any) -> Any: ...

