# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrQweb(models.AbstractModel):
    def _get_template_cache_keys(self: Any) -> Any: ...
    def _get_template(self: Any, template: Any) -> Any: ...
    def _post_processing_att(self: Any, tagName: Any, atts: Any) -> Any: ...
    def _get_bundles_to_pregenarate(self: Any) -> Any: ...
    def _prepare_frontend_environment(self: Any, values: Any) -> Any: ...
    def _adapt_style_background_image(self: Any, atts: Any, url_adapter: Any) -> Any: ...

