# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    auth_signup_uninvited: Any
    website_id: Any
    website_name: Any
    website_domain: Any
    website_homepage_url: Any
    website_company_id: Any
    website_logo: Any
    language_ids: Any
    website_language_count: Any
    website_default_lang_id: Any
    website_default_lang_code: Any
    shared_user_account: Any
    website_cookies_bar: Any
    website_block_third_party_domains: Any
    google_analytics_key: Any
    google_search_console: Any
    plausible_shared_key: Any
    plausible_site: Any
    cdn_activated: Any
    cdn_url: Any
    cdn_filters: Any
    favicon: Any
    social_default_image: Any
    group_multi_website: Any
    has_google_analytics: Any
    has_google_search_console: Any
    has_default_share_image: Any
    has_plausible_shared_key: Any
    module_website_livechat: Any
    def _default_website(self: Any) -> Any: ...
    def _compute_shared_user_account(self: Any) -> Any: ...
    def _onchange_shared_key(self: Any) -> Any: ...
    def _inverse_shared_user_account(self: Any) -> Any: ...
    def _compute_auth_signup_uninvited(self: Any) -> Any: ...
    def _inverse_auth_signup_uninvited(self: Any) -> Any: ...
    def _compute_has_plausible_shared_key(self: Any) -> Any: ...
    def _inverse_has_plausible_shared_key(self: Any) -> Any: ...
    def _compute_has_google_analytics(self: Any) -> Any: ...
    def _inverse_has_google_analytics(self: Any) -> Any: ...
    def _compute_has_google_search_console(self: Any) -> Any: ...
    def _inverse_has_google_search_console(self: Any) -> Any: ...
    def _compute_has_default_share_image(self: Any) -> Any: ...
    def _inverse_has_default_share_image(self: Any) -> Any: ...
    def _onchange_language_ids(self: Any) -> Any: ...
    def action_website_create_new(self: Any) -> Any: ...
    def action_open_robots(self: Any) -> Any: ...
    def action_open_blocked_third_party_domains(self: Any) -> Any: ...

