# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrAsset(models.Model):
    theme_template_id: Any

class IrAttachment(models.Model):
    key: Any
    theme_template_id: Any

class IrUiView(models.Model):
    theme_template_id: Any
    def write(self: Any, vals: Any) -> Any: ...

class ThemeIrAsset(models.Model):
    key: Any
    name: Any
    bundle: Any
    directive: Any
    path: Any
    target: Any
    active: Any
    sequence: Any
    copy_ids: Any
    def _convert_to_base_model(self: Any, website: Any, **kwargs: Any) -> Any: ...

class ThemeIrAttachment(models.Model):
    name: Any
    key: Any
    url: Any
    copy_ids: Any
    def _convert_to_base_model(self: Any, website: Any, **kwargs: Any) -> Any: ...

class ThemeIrUiView(models.Model):
    name: Any
    key: Any
    type: Any
    priority: Any
    mode: Any
    active: Any
    arch: Any
    arch_fs: Any
    inherit_id: Any
    copy_ids: Any
    customize_show: Any
    def compute_arch_fs(self: Any) -> Any: ...
    def _convert_to_base_model(self: Any, website: Any, **kwargs: Any) -> Any: ...

class ThemeUtils(models.AbstractModel):
    def _post_copy(self: Any, mod: Any) -> Any: ...
    def _reset_default_config(self: Any) -> Any: ...
    def _toggle_asset(self: Any, key: Any, active: Any) -> Any: ...
    def _toggle_view(self: Any, xml_id: Any, active: Any) -> Any: ...
    def enable_asset(self: Any, name: Any) -> Any: ...
    def disable_asset(self: Any, name: Any) -> Any: ...
    def enable_view(self: Any, xml_id: Any) -> Any: ...
    def disable_view(self: Any, xml_id: Any) -> Any: ...

class ThemeWebsiteMenu(models.Model):
    name: Any
    url: Any
    page_id: Any
    new_window: Any
    sequence: Any
    parent_id: Any
    mega_menu_content: Any
    mega_menu_classes: Any
    use_main_menu_as_parent: Any
    copy_ids: Any
    def _convert_to_base_model(self: Any, website: Any, **kwargs: Any) -> Any: ...

class ThemeWebsitePage(models.Model):
    url: Any
    view_id: Any
    website_indexed: Any
    is_published: Any
    is_new_page_template: Any
    copy_ids: Any
    def _convert_to_base_model(self: Any, website: Any, **kwargs: Any) -> Any: ...

class WebsiteMenu(models.Model):
    theme_template_id: Any

class WebsitePage(models.Model):
    theme_template_id: Any

