# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrModel(models.Model):
    website_form_access: Any
    website_form_default_field_id: Any
    website_form_label: Any
    website_form_key: Any
    def _get_form_writable_fields(self: Any, property_origins: Any = ...) -> Any: ...
    def get_authorized_fields(self: Any, model_name: Any, property_origins: Any) -> Any: ...
    def get_compatible_form_models(self: Any) -> Any: ...

class IrModelFields(models.Model):
    website_form_blacklisted: Any
    def init(self: Any) -> Any: ...
    def _check_if_used_in_website_form(self: Any) -> Any: ...
    def formbuilder_whitelist(self: Any, model: Any, fields: Any) -> Any: ...

class Website(models.Model):
    def _website_form_last_record(self: Any) -> Any: ...

