# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class WebsitePageProperties(models.TransientModel):
    target_model_id: Any
    name: Any
    url: Any
    date_publish: Any
    website_indexed: Any
    visibility: Any
    visibility_password_display: Any
    group_ids: Any
    is_new_page_template: Any
    old_url: Any
    redirect_old_url: Any
    redirect_type: Any
    def _compute_is_homepage(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...

class WebsitePagePropertiesBase(models.TransientModel):
    target_model_id: Any
    website_id: Any
    menu_ids: Any
    is_in_menu: Any
    url: Any
    is_homepage: Any
    can_publish: Any
    is_published: Any
    def _selection_target_model_id(self: Any) -> Any: ...
    def _get_menu_domain(self: Any, url: Any = ...) -> Any: ...
    def _compute_menu_ids(self: Any) -> Any: ...
    def _compute_is_in_menu(self: Any) -> Any: ...
    def _inverse_is_in_menu(self: Any) -> Any: ...
    def _compute_is_homepage(self: Any) -> Any: ...
    def _inverse_is_homepage(self: Any) -> Any: ...
    def _compute_can_publish(self: Any) -> Any: ...
    def _compute_is_published(self: Any) -> Any: ...
    def _inverse_is_published(self: Any) -> Any: ...
    def _get_ir_ui_view_unpublish_group(self: Any) -> Any: ...
    def _is_ir_ui_view_unpublished(self: Any, view: Any) -> Any: ...
    def _is_ir_ui_view_published(self: Any, view: Any) -> Any: ...

