# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class WebsiteConfiguratorFeature(models.Model):
    sequence: Any
    name: Any
    description: Any
    icon: Any
    iap_page_code: Any
    website_config_preselection: Any
    page_view_id: Any
    module_id: Any
    feature_url: Any
    menu_sequence: Any
    menu_company: Any
    def _check_module_xor_page_view(self: Any) -> Any: ...
    def _process_svg(theme: Any, colors: Any, image_mapping: Any) -> Any: ...

