# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrAttachment(models.Model):
    local_url: Any
    image_src: Any
    image_width: Any
    image_height: Any
    original_id: Any
    def _compute_local_url(self: Any) -> Any: ...
    def _compute_image_src(self: Any) -> Any: ...
    def _compute_image_size(self: Any) -> Any: ...
    def _get_media_info(self: Any) -> Any: ...
    def _can_bypass_rights_on_media_dialog(self: Any, **kwargs: Any) -> Any: ...

