# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductPublicCategory(models.Model):
    name: Any
    cover_image: Any
    sequence: Any
    parent_id: Any
    child_id: Any
    parent_path: Any
    parents_and_self: Any
    product_tmpl_ids: Any
    has_published_products: Any
    website_description: Any
    website_footer: Any
    show_category_title: Any
    show_category_description: Any
    align_category_content: Any
    def _default_sequence(self: Any) -> Any: ...
    def _compute_parents_and_self(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def _compute_has_published_products(self: Any) -> Any: ...
    def check_parent_id(self: Any) -> Any: ...
    def _search_has_published_products(self: Any, operator: Any, value: Any) -> Any: ...
    def _search_get_detail(self: Any, website: Any, order: Any, options: Any) -> Any: ...
    def _search_render_results(self: Any, fetch_fields: Any, mapping: Any, icon: Any, limit: Any) -> Any: ...
    def get_available_snippet_categories(self: Any, website_id: Any) -> Any: ...
    def _get_available_category_domain(self: Any, website_id: Any) -> Any: ...

