# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductImage(models.Model):
    name: Any
    sequence: Any
    image_1920: Any
    product_tmpl_id: Any
    product_variant_id: Any
    video_url: Any
    embed_code: Any
    can_image_1024_be_zoomed: Any
    def _compute_can_image_1024_be_zoomed(self: Any) -> Any: ...
    def _compute_embed_code(self: Any) -> Any: ...
    def _onchange_video_url(self: Any) -> Any: ...
    def _check_valid_video_url(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...

