# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    group_show_uom_price: Any
    group_product_price_comparison: Any
    group_gmc_feed: Any
    module_website_sale_autocomplete: Any
    module_website_sale_collect: Any
    add_to_cart_action: Any
    cart_recovery_mail_template: Any
    cart_abandoned_delay: Any
    send_abandoned_cart_email: Any
    salesperson_id: Any
    salesteam_id: Any
    website_sale_prevent_zero_price_sale: Any
    website_sale_contact_us_button_url: Any
    show_line_subtotals_tax_selection: Any
    confirmation_email_template_id: Any
    account_on_checkout: Any
    ecommerce_access: Any
    def set_values(self: Any) -> Any: ...
    def _compute_account_on_checkout(self: Any) -> Any: ...
    def _inverse_account_on_checkout(self: Any) -> Any: ...
    def action_view_delivery_provider_modules(self: Any) -> Any: ...
    def action_open_abandoned_cart_mail_template(self: Any) -> Any: ...
    def action_open_extra_info(self: Any) -> Any: ...
    def action_open_sale_mail_templates(self: Any) -> Any: ...
    def action_open_product_feeds(self: Any) -> Any: ...

