# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class WebsiteCheckoutStep(models.Model):
    name: Any
    sequence: Any
    step_href: Any
    main_button_label: Any
    back_button_label: Any
    website_id: Any
    def _get_next_checkout_step(self: Any, allowed_steps_domain: Any) -> Any: ...
    def _get_previous_checkout_step(self: Any, allowed_steps_domain: Any) -> Any: ...

