# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class OnboardingOnboardingStep(models.Model):
    onboarding_ids: Any
    title: Any
    description: Any
    button_text: Any
    done_icon: Any
    done_text: Any
    step_image: Any
    step_image_filename: Any
    step_image_alt: Any
    panel_step_open_action_name: Any
    current_progress_step_id: Any
    current_step_state: Any
    progress_ids: Any
    is_per_company: Any
    sequence: Any
    def _compute_current_progress(self: Any) -> Any: ...
    def check_step_on_onboarding_has_action(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def action_set_just_done(self: Any) -> Any: ...
    def action_validate_step(self: Any, xml_id: Any) -> Any: ...
    def _get_placeholder_filename(self: Any, field: Any) -> Any: ...
    def _create_progress_steps(self: Any) -> Any: ...

