# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class OnboardingOnboarding(models.Model):
    name: Any
    route_name: Any
    step_ids: Any
    text_completed: Any
    is_per_company: Any
    panel_close_action_name: Any
    current_progress_id: Any
    current_onboarding_state: Any
    is_onboarding_closed: Any
    progress_ids: Any
    sequence: Any
    def _prepare_rendering_values(self: Any) -> Any: ...
    def _compute_is_per_company(self: Any) -> Any: ...
    def _compute_current_progress(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def action_close(self: Any) -> Any: ...
    def action_close_panel(self: Any, xmlid: Any) -> Any: ...
    def action_refresh_progress_ids(self: Any) -> Any: ...
    def action_toggle_visibility(self: Any) -> Any: ...
    def _search_or_create_progress(self: Any) -> Any: ...
    def _create_progress(self: Any) -> Any: ...

