# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class CrmTeam(models.Model):
    invoiced: Any
    invoiced_target: Any
    sale_order_count: Any
    def _compute_dashboard_button_name(self: Any) -> Any: ...
    def action_primary_channel_button(self: Any) -> Any: ...
    def _compute_invoiced(self: Any) -> Any: ...
    def _compute_sale_order_count(self: Any) -> Any: ...
    def _in_sale_scope(self: Any) -> Any: ...
    def update_invoiced_target(self: Any, value: Any) -> Any: ...
    def _unlink_except_used_for_sales(self: Any) -> Any: ...

