# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductCombo(models.Model):
    name: Any
    sequence: Any
    company_id: Any
    combo_item_ids: Any
    combo_item_count: Any
    currency_id: Any
    base_price: Any
    def _compute_combo_item_count(self: Any) -> Any: ...
    def _compute_currency_id(self: Any) -> Any: ...
    def _compute_base_price(self: Any) -> Any: ...
    def _check_combo_item_ids_not_empty(self: Any) -> Any: ...
    def _check_combo_item_ids_no_duplicates(self: Any) -> Any: ...
    def _check_company_id(self: Any) -> Any: ...

