# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductTemplateAttributeValue(models.Model):
    ptav_active: Any
    name: Any
    product_attribute_value_id: Any
    attribute_line_id: Any
    price_extra: Any
    currency_id: Any
    exclude_for: Any
    product_tmpl_id: Any
    attribute_id: Any
    ptav_product_variant_ids: Any
    html_color: Any
    is_custom: Any
    display_type: Any
    color: Any
    image: Any
    def _get_default_color(self: Any) -> Any: ...
    def _check_valid_values(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def _only_active(self: Any) -> Any: ...
    def _without_no_variant_attributes(self: Any) -> Any: ...
    def _ids2str(self: Any) -> Any: ...
    def _get_combination_name(self: Any) -> Any: ...
    def _filter_single_value_lines(self: Any) -> Any: ...
    def _is_from_single_value_line(self: Any, only_active: Any = ...) -> Any: ...

