# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductAttributeValue(models.Model):
    name: Any
    sequence: Any
    attribute_id: Any
    pav_attribute_line_ids: Any
    default_extra_price: Any
    is_custom: Any
    html_color: Any
    display_type: Any
    color: Any
    image: Any
    active: Any
    is_used_on_products: Any
    default_extra_price_changed: Any
    def _get_default_color(self: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def _compute_is_used_on_products(self: Any) -> Any: ...
    def _compute_default_extra_price_changed(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def check_is_used_on_products(self: Any) -> Any: ...
    def _unlink_except_used_on_product(self: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def _without_no_variant_attributes(self: Any) -> Any: ...
    def action_add_to_products(self: Any) -> Any: ...
    def action_update_prices(self: Any) -> Any: ...

