# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductSupplierinfo(models.Model):
    partner_id: Any
    product_name: Any
    product_code: Any
    sequence: Any
    product_uom_id: Any
    min_qty: Any
    price: Any
    price_discounted: Any
    company_id: Any
    currency_id: Any
    date_start: Any
    date_end: Any
    product_id: Any
    product_tmpl_id: Any
    product_variant_count: Any
    delay: Any
    discount: Any
    def _compute_product_uom_id(self: Any) -> Any: ...
    def _compute_price(self: Any) -> Any: ...
    def _compute_price_discounted(self: Any) -> Any: ...
    def _compute_product_tmpl_id(self: Any) -> Any: ...
    def _compute_product_id(self: Any) -> Any: ...
    def _onchange_product_tmpl_id(self: Any) -> Any: ...
    def get_import_templates(self: Any) -> Any: ...
    def _sanitize_vals(self: Any, vals: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _get_filtered_supplier(self: Any, company_id: Any, product_id: Any, params: Any = ...) -> Any: ...

