# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ProductAttribute(models.Model):
    name: Any
    active: Any
    create_variant: Any
    display_type: Any
    sequence: Any
    value_ids: Any
    template_value_ids: Any
    attribute_line_ids: Any
    product_tmpl_ids: Any
    number_related_products: Any
    def _compute_number_related_products(self: Any) -> Any: ...
    def _compute_products(self: Any) -> Any: ...
    def _onchange_display_type(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _unlink_except_used_on_product(self: Any) -> Any: ...
    def action_archive(self: Any) -> Any: ...
    def action_open_product_template_attribute_lines(self: Any) -> Any: ...
    def _without_no_variant_attributes(self: Any) -> Any: ...

