# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailTemplatePreview(models.TransientModel):
    mail_template_id: Any
    model_id: Any
    resource_ref: Any
    lang: Any
    no_record: Any
    error_msg: Any
    subject: Any
    email_from: Any
    email_to: Any
    email_cc: Any
    reply_to: Any
    scheduled_date: Any
    body_html: Any
    attachment_ids: Any
    has_attachments: Any
    has_several_languages_installed: Any
    partner_ids: Any
    def _selection_target_model(self: Any) -> Any: ...
    def _selection_languages(self: Any) -> Any: ...
    def _compute_no_record(self: Any) -> Any: ...
    def _compute_mail_template_fields(self: Any) -> Any: ...
    def _compute_has_attachments(self: Any) -> Any: ...
    def _compute_has_several_languages_installed(self: Any) -> Any: ...
    def _compute_resource_ref(self: Any) -> Any: ...
    def _set_mail_attributes(self: Any, values: Any = ...) -> Any: ...

