# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class CrmTeamMember(models.Model):
    crm_team_id: Any
    user_id: Any
    user_in_teams_ids: Any
    user_company_ids: Any
    active: Any
    is_membership_multi: Any
    member_warning: Any
    image_1920: Any
    image_128: Any
    name: Any
    email: Any
    phone: Any
    company_id: Any
    def _constrains_membership(self: Any) -> Any: ...
    def _constrains_company_membership(self: Any) -> Any: ...
    def _compute_user_in_teams_ids(self: Any) -> Any: ...
    def _compute_user_company_ids(self: Any) -> Any: ...
    def _compute_is_membership_multi(self: Any) -> Any: ...
    def _compute_member_warning(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _synchronize_memberships(self: Any, user_team_ids: Any) -> Any: ...

