# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResUsers(models.Model):
    crm_team_ids: Any
    crm_team_member_ids: Any
    sale_team_id: Any
    def action_archive(self: Any) -> Any: ...
    def _compute_crm_team_ids(self: Any) -> Any: ...
    def _search_crm_team_ids(self: Any, operator: Any, value: Any) -> Any: ...
    def _compute_sale_team_id(self: Any) -> Any: ...

