# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class FetchmailServer(models.Model):
    name: Any
    active: Any
    state: Any
    server: Any
    port: Any
    server_type: Any
    server_type_info: Any
    is_ssl: Any
    attach: Any
    original: Any
    date: Any
    error_date: Any
    error_message: Any
    user: Any
    password: Any
    object_id: Any
    priority: Any
    message_ids: Any
    configuration: Any
    script: Any
    def _compute_server_type_info(self: Any) -> Any: ...
    def onchange_server_type(self: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def set_draft(self: Any) -> Any: ...
    def _connect__(self: Any, allow_archived: Any = ...) -> Any: ...
    def _imap_login__(self: Any, connection: Any) -> Any: ...
    def button_confirm_login(self: Any) -> Any: ...
    def fetch_mail(self: Any) -> Any: ...
    def _fetch_mails(self: Any, **kwargs: Any) -> Any: ...
    def _fetch_mail(self: Any, batch_limit: Any = ...) -> Any: ...
    def _get_connection_type(self: Any) -> Any: ...
    def _update_cron(self: Any) -> Any: ...

