# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrModel(models.Model):
    is_mail_thread: Any
    is_mail_activity: Any
    is_mail_blacklist: Any
    def unlink(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _reflect_model_params(self: Any, model: Any) -> Any: ...
    def _instanciate_attrs(self: Any, model_data: Any) -> Any: ...
    def _get_model_definitions(self: Any, model_names_to_fetch: Any) -> Any: ...
    def _get_definitions(self: Any, model_names: Any) -> Any: ...

