# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrMail_Server(models.Model):
    mail_template_ids: Any
    owner_user_id: Any
    owner_limit_time: Any
    owner_limit_count: Any
    def _active_usages_compute(self: Any) -> Any: ...
    def _get_test_email_from(self: Any) -> Any: ...
    def _check_forced_mail_server(self: Any, mail_server: Any, allow_archived: Any, smtp_from: Any) -> Any: ...
    def _get_default_bounce_address(self: Any) -> Any: ...
    def _get_default_from_address(self: Any) -> Any: ...
    def _find_mail_server_allowed_domain(self: Any) -> Any: ...
    def _filter_mail_servers_fallback(self: Any, servers: Any) -> Any: ...
    def _get_personal_mail_servers_limit(self: Any) -> Any: ...

