# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrQweb(models.AbstractModel):
    def _get_template_cache_keys(self: Any) -> Any: ...
    def _compile_expr(self: Any, expr: Any, raise_on_missing: Any = ...) -> Any: ...
    def _compile_directive(self: Any, el: Any, compile_context: Any, directive: Any, level: Any) -> Any: ...
    def _compile_directive_att(self: Any, el: Any, compile_context: Any, level: Any) -> Any: ...
    def _compile_directive_out(self: Any, el: Any, compile_context: Any, level: Any) -> Any: ...
    def _is_expression_allowed(self: Any, expression: Any, model: Any) -> Any: ...

