# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailMessageSchedule(models.Model):
    mail_message_id: Any
    notification_parameters: Any
    scheduled_datetime: Any
    def create(self: Any, vals_list: Any) -> Any: ...
    def _send_notifications_cron(self: Any) -> Any: ...
    def force_send(self: Any) -> Any: ...
    def _send_notifications(self: Any, default_notify_kwargs: Any = ...) -> Any: ...
    def _send_message_notifications(self: Any, messages: Any, default_notify_kwargs: Any = ...) -> Any: ...
    def _update_message_scheduled_datetime(self: Any, messages: Any, new_datetime: Any) -> Any: ...
    def _group_by_model(self: Any) -> Any: ...

