# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailActivityPlan(models.Model):
    name: Any
    company_id: Any
    template_ids: Any
    active: Any
    res_model_id: Any
    res_model: Any
    steps_count: Any
    has_user_on_demand: Any
    def _get_model_selection(self: Any) -> Any: ...
    def _compute_res_model_id(self: Any) -> Any: ...
    def _check_res_model_compatibility_with_templates(self: Any) -> Any: ...
    def _compute_steps_count(self: Any) -> Any: ...
    def _compute_has_user_on_demand(self: Any) -> Any: ...
    def copy_data(self: Any, default: Any = ...) -> Any: ...

