# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailThreadMainAttachment(models.AbstractModel):
    message_main_attachment_id: Any
    def _message_post_after_hook(self: Any, message: Any, msg_values: Any) -> Any: ...
    def _message_set_main_attachment_id(self: Any, attachments: Any, force: Any = ..., filter_xml: Any = ...) -> Any: ...
    def _thread_to_store(self: Any, store: Any, fields: Any, *, request_list: Any = ...) -> Any: ...

