# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailActivityType(models.Model):
    category: Any
    name: Any
    summary: Any
    sequence: Any
    active: Any
    create_uid: Any
    delay_count: Any
    delay_unit: Any
    delay_label: Any
    delay_from: Any
    icon: Any
    decoration_type: Any
    res_model: Any
    triggered_next_type_id: Any
    chaining_type: Any
    suggested_next_type_ids: Any
    previous_type_ids: Any
    mail_template_ids: Any
    default_user_id: Any
    default_note: Any
    initial_res_model: Any
    res_model_change: Any
    def _get_model_selection(self: Any) -> Any: ...
    def _check_activity_type_res_model(self: Any) -> Any: ...
    def _onchange_res_model(self: Any) -> Any: ...
    def _compute_initial_res_model(self: Any) -> Any: ...
    def _compute_delay_label(self: Any) -> Any: ...
    def _compute_suggested_next_type_ids(self: Any) -> Any: ...
    def _inverse_suggested_next_type_ids(self: Any) -> Any: ...
    def _compute_triggered_next_type_id(self: Any) -> Any: ...
    def _inverse_triggered_next_type_id(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _unlink_except_todo(self: Any) -> Any: ...
    def action_archive(self: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def _get_date_deadline(self: Any) -> Any: ...
    def _get_model_info_by_xmlid(self: Any) -> Any: ...

