# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailNotification(models.Model):
    author_id: Any
    mail_message_id: Any
    mail_mail_id: Any
    res_partner_id: Any
    mail_email_address: Any
    notification_type: Any
    notification_status: Any
    is_read: Any
    read_date: Any
    failure_type: Any
    failure_reason: Any
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _gc_notifications(self: Any, max_age_days: Any = ...) -> Any: ...
    def format_failure_reason(self: Any) -> Any: ...
    def _filtered_for_web_client(self: Any) -> Any: ...
    def _to_store_defaults(self: Any, target: Any) -> Any: ...

