# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailActivityPlanTemplate(models.Model):
    plan_id: Any
    res_model: Any
    company_id: Any
    sequence: Any
    activity_type_id: Any
    delay_count: Any
    delay_unit: Any
    delay_from: Any
    icon: Any
    summary: Any
    responsible_type: Any
    responsible_id: Any
    note: Any
    next_activity_ids: Any
    def _check_activity_type_res_model(self: Any) -> Any: ...
    def _check_responsible(self: Any) -> Any: ...
    def _compute_next_activity_ids(self: Any) -> Any: ...
    def _compute_note(self: Any) -> Any: ...
    def _compute_responsible_id(self: Any) -> Any: ...
    def _compute_responsible_type(self: Any) -> Any: ...
    def _compute_summary(self: Any) -> Any: ...
    def _get_date_deadline(self: Any, base_date: Any = ...) -> Any: ...
    def _determine_responsible(self: Any, on_demand_responsible: Any, applied_on_record: Any) -> Any: ...

