# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailComposerMixin(models.AbstractModel):
    subject: Any
    body: Any
    body_has_template_value: Any
    template_id: Any
    lang: Any
    is_mail_template_editor: Any
    can_edit_body: Any
    def _compute_subject(self: Any) -> Any: ...
    def _compute_body(self: Any) -> Any: ...
    def _compute_body_has_template_value(self: Any) -> Any: ...
    def _compute_lang(self: Any) -> Any: ...
    def _compute_is_mail_template_editor(self: Any) -> Any: ...
    def _compute_can_edit_body(self: Any) -> Any: ...
    def _render_lang(self: Any, res_ids: Any, engine: Any = ...) -> Any: ...
    def _render_field(self: Any, field: Any, res_ids: Any, *args: Any, **kwargs: Any) -> Any: ...

