# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailTrackingValue(models.Model):
    field_id: Any
    field_info: Any
    old_value_integer: Any
    old_value_float: Any
    old_value_char: Any
    old_value_text: Any
    old_value_datetime: Any
    new_value_integer: Any
    new_value_float: Any
    new_value_char: Any
    new_value_text: Any
    new_value_datetime: Any
    currency_id: Any
    mail_message_id: Any
    def _filter_has_field_access(self: Any, env: Any) -> Any: ...
    def _filter_free_field_access(self: Any) -> Any: ...
    def _create_tracking_values(self: Any, initial_value: Any, new_value: Any, col_name: Any, col_info: Any, record: Any) -> Any: ...
    def _create_tracking_values_property(self: Any, initial_value: Any, col_name: Any, col_info: Any, record: Any) -> Any: ...
    def _tracking_value_format(self: Any) -> Any: ...
    def _tracking_value_format_model(self: Any, model: Any) -> Any: ...
    def _format_display_value(self: Any, field_type: Any, new: Any = ...) -> Any: ...

