# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class MailPresence(models.Model):
    user_id: Any
    guest_id: Any
    last_poll: Any
    last_presence: Any
    status: Any
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def _try_update_presence(self: Any, user_or_guest: Any, inactivity_period: Any = ...) -> Any: ...
    def _update_presence(self: Any, user_or_guest: Any, inactivity_period: Any = ...) -> Any: ...
    def _send_presence(self: Any, im_status: Any = ..., bus_target: Any = ...) -> Any: ...
    def _send_status_updated_notification(self: Any, *, guest_or_user: Any = ..., status: Any = ..., bus_target: Any = ...) -> Any: ...
    def _gc_bus_presence(self: Any) -> Any: ...

