# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResUsersSettings(models.Model):
    is_discuss_sidebar_category_channel_open: Any
    is_discuss_sidebar_category_chat_open: Any
    push_to_talk_key: Any
    use_push_to_talk: Any
    voice_active_duration: Any
    volume_settings_ids: Any
    channel_notifications: Any
    def _format_settings(self: Any, fields_to_format: Any) -> Any: ...
    def set_res_users_settings(self: Any, new_settings: Any) -> Any: ...
    def set_volume_setting(self: Any, partner_id: Any, volume: Any, guest_id: Any = ...) -> Any: ...

