# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    external_email_server_default: Any
    fail_counter: Any
    alias_domain_id: Any
    module_google_gmail: Any
    module_microsoft_outlook: Any
    restrict_template_rendering: Any
    use_twilio_rtc_servers: Any
    twilio_account_sid: Any
    twilio_account_token: Any
    use_sfu_server: Any
    sfu_server_url: Any
    sfu_server_key: Any
    email_primary_color: Any
    email_secondary_color: Any
    tenor_api_key: Any
    google_translate_api_key: Any
    def _compute_fail_counter(self: Any) -> Any: ...
    def open_email_layout(self: Any) -> Any: ...
    def open_mail_templates(self: Any) -> Any: ...

