# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class Base(models.AbstractModel):
    def _phone_get_number_fields(self: Any) -> Any: ...
    def _phone_get_country(self: Any) -> Any: ...
    def _phone_get_country_field(self: Any) -> Any: ...
    def _phone_format(self: Any, fname: Any = ..., number: Any = ..., country: Any = ..., force_format: Any = ..., raise_exception: Any = ...) -> Any: ...
    def _phone_format_number(self: Any, number: Any, country: Any, force_format: Any = ..., raise_exception: Any = ...) -> Any: ...

