# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PaymentLinkWizard(models.TransientModel):
    invoice_amount_due: Any
    open_installments: Any
    open_installments_preview: Any
    display_open_installments: Any
    has_eligible_epd: Any
    discount_date: Any
    epd_info: Any
    def _compute_warning_message(self: Any) -> Any: ...
    def _compute_invoice_amount_due(self: Any) -> Any: ...
    def _compute_open_installments_preview(self: Any) -> Any: ...
    def _compute_epd_info(self: Any) -> Any: ...
    def _compute_display_open_installments(self: Any) -> Any: ...
    def _prepare_url(self: Any, base_url: Any, related_document: Any) -> Any: ...
    def _prepare_query_params(self: Any, related_document: Any) -> Any: ...
    def _prepare_access_token(self: Any) -> Any: ...
    def _prepare_anchor(self: Any) -> Any: ...

