# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class PaymentRefundWizard(models.TransientModel):
    payment_id: Any
    transaction_id: Any
    payment_amount: Any
    refunded_amount: Any
    amount_available_for_refund: Any
    amount_to_refund: Any
    currency_id: Any
    support_refund: Any
    has_pending_refund: Any
    def _check_amount_to_refund_within_boundaries(self: Any) -> Any: ...
    def _compute_refunded_amount(self: Any) -> Any: ...
    def _compute_amount_to_refund(self: Any) -> Any: ...
    def _compute_support_refund(self: Any) -> Any: ...
    def _compute_has_pending_refund(self: Any) -> Any: ...
    def action_refund(self: Any) -> Any: ...

