# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class SaleReport(models.Model):
    name: Any
    date: Any
    partner_id: Any
    company_id: Any
    pricelist_id: Any
    team_id: Any
    user_id: Any
    state: Any
    invoice_status: Any
    campaign_id: Any
    medium_id: Any
    source_id: Any
    commercial_partner_id: Any
    country_id: Any
    industry_id: Any
    partner_zip: Any
    state_id: Any
    order_reference: Any
    categ_id: Any
    product_id: Any
    product_tmpl_id: Any
    product_uom_id: Any
    product_uom_qty: Any
    qty_to_deliver: Any
    qty_delivered: Any
    qty_to_invoice: Any
    qty_invoiced: Any
    price_subtotal: Any
    price_total: Any
    untaxed_amount_to_invoice: Any
    untaxed_amount_invoiced: Any
    line_invoice_status: Any
    weight: Any
    volume: Any
    price_unit: Any
    discount: Any
    discount_amount: Any
    nbr: Any
    currency_id: Any
    def _get_done_states(self: Any) -> Any: ...
    def _with_sale(self: Any) -> Any: ...
    def _select_sale(self: Any) -> Any: ...
    def _case_value_or_one(self: Any, value: Any) -> Any: ...
    def _select_additional_fields(self: Any) -> Any: ...
    def _from_sale(self: Any) -> Any: ...
    def _where_sale(self: Any) -> Any: ...
    def _group_by_sale(self: Any) -> Any: ...
    def _query(self: Any) -> Any: ...
    def _table_query(self: Any) -> Any: ...
    def action_open_order(self: Any) -> Any: ...

