# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    default_invoice_policy: Any
    group_auto_done_setting: Any
    group_discount_per_so_line: Any
    group_proforma_sales: Any
    group_warning_sale: Any
    automatic_invoice: Any
    invoice_mail_template_id: Any
    quotation_validity_days: Any
    portal_confirmation_sign: Any
    portal_confirmation_pay: Any
    prepayment_percent: Any
    downpayment_account_id: Any
    module_delivery: Any
    module_delivery_bpost: Any
    module_delivery_dhl: Any
    module_delivery_easypost: Any
    module_delivery_envia: Any
    module_delivery_fedex_rest: Any
    module_delivery_sendcloud: Any
    module_delivery_shiprocket: Any
    module_delivery_starshipit: Any
    module_delivery_ups_rest: Any
    module_delivery_usps_rest: Any
    module_product_email_template: Any
    module_sale_amazon: Any
    module_sale_commission: Any
    module_sale_gelato: Any
    module_sale_loyalty: Any
    module_sale_margin: Any
    module_sale_pdf_quote_builder: Any
    module_sale_product_matrix: Any
    module_sale_shopee: Any
    def set_values(self: Any) -> Any: ...
    def _onchange_group_discount_per_so_line(self: Any) -> Any: ...
    def _onchange_group_product_variant(self: Any) -> Any: ...
    def _onchange_portal_confirmation_pay(self: Any) -> Any: ...
    def _onchange_prepayment_percent(self: Any) -> Any: ...
    def _onchange_quotation_validity_days(self: Any) -> Any: ...
    def action_sale_start_payment_onboarding(self: Any) -> Any: ...

