# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class SaleOrderDiscount(models.TransientModel):
    sale_order_id: Any
    company_id: Any
    currency_id: Any
    discount_amount: Any
    discount_percentage: Any
    discount_type: Any
    def _check_discount_amount(self: Any) -> Any: ...
    def _prepare_discount_product_values(self: Any) -> Any: ...
    def _prepare_global_discount_so_lines(self: Any, base_lines: Any) -> Any: ...
    def _get_discount_product(self: Any) -> Any: ...
    def _create_discount_lines(self: Any) -> Any: ...
    def action_apply_discount(self: Any) -> Any: ...

