# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ChooseDeliveryCarrier(models.TransientModel):
    order_id: Any
    partner_id: Any
    carrier_id: Any
    delivery_type: Any
    delivery_price: Any
    display_price: Any
    currency_id: Any
    company_id: Any
    available_carrier_ids: Any
    invoicing_message: Any
    delivery_message: Any
    total_weight: Any
    weight_uom_name: Any
    def _get_default_weight_uom(self: Any) -> Any: ...
    def _onchange_carrier_id(self: Any) -> Any: ...
    def _onchange_order_id(self: Any) -> Any: ...
    def _compute_invoicing_message(self: Any) -> Any: ...
    def _compute_available_carrier(self: Any) -> Any: ...
    def _get_delivery_rate(self: Any) -> Any: ...
    def update_price(self: Any) -> Any: ...
    def button_confirm(self: Any) -> Any: ...

