# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class Web_TourTour(models.Model):
    name: Any
    step_ids: Any
    url: Any
    sharing_url: Any
    rainbow_man_message: Any
    sequence: Any
    custom: Any
    user_consumed_ids: Any
    def _compute_sharing_url(self: Any) -> Any: ...
    def consume(self: Any, tourName: Any) -> Any: ...
    def get_current_tour(self: Any) -> Any: ...
    def get_tour_json_by_name(self: Any, tour_name: Any) -> Any: ...
    def _get_tour_json(self: Any) -> Any: ...
    def export_js_file(self: Any) -> Any: ...

class Web_TourTourStep(models.Model):
    trigger: Any
    content: Any
    tooltip_position: Any
    tour_id: Any
    run: Any
    sequence: Any
    def get_steps_json(self: Any) -> Any: ...

