#!/usr/bin/env python3
# This software is distributed under the terms of the Affero General Public License (AGPL-3).
# SPDX-License-Identifier: AGPL-3.0-or-later

import os
import sys
import ast

# Repo-relative paths of files that deliberately live in a tests/
# directory but are NOT Odoo tests, so not importing them from
# __init__.py is correct, not an oversight. Each entry must carry its
# own in-file explanation of why it's here (this checker can't tell
# "forgotten" from "deliberate" on its own).
EXCLUDED_FILES = {
    # A real-browser Playwright verification script for NoiseXXInitiator
    # (see TRANSMITTER_HIJACK_PREVENTION.md section 1) that needs a real
    # headless Chromium instance and real ES module loading over HTTP,
    # neither of which Odoo's own test runner provides -- its own module
    # docstring says so explicitly: "Not an Odoo test (no `test_` prefix,
    # not imported from an __init__.py)". Run directly, not discovered.
    "ham_shack/tests/verify_noise_xx_handshake.py",
    # Real-browser Playwright verification scripts for sanitizeLessonHtml()
    # and the <story-chapter>/<knowledge-check> web components in
    # static/src/js/components/story-components.js -- their own module
    # docstrings say so explicitly: "Not an Odoo test (no `test_` prefix,
    # not imported from an __init__.py)". Formerly lived in the now-retired
    # ham_training_auxcomm module (whose tests/ directory had no
    # __init__.py at all, so this check never ran against them); moved
    # into ham_training/tests/ along with the rest of that module's
    # content, which does have an __init__.py, so the exclusion needs to
    # be explicit here now. Run directly, not discovered.
    "ham_training/tests/verify_sanitizer.py",
    "ham_training/tests/verify_story_components.py",
}


def get_imported_names(init_path):
    imported = set()
    try:
        with open(init_path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read(), filename=init_path)
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                if (
                    node.level == 1
                ):  # from . import my_model or from .my_model import my_func
                    if node.module:
                        imported.add(node.module.split(".")[0])
                    else:
                        for alias in node.names:
                            imported.add(alias.name)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    imported.add(alias.name)
    except (SyntaxError, OSError) as e:
        print(f"Error parsing {init_path}: {e}")
    return imported


def main():
    if len(sys.argv) < 2:
        print("Usage: check_init_imports.py <repo_root>")
        sys.exit(1)

    repo_root = sys.argv[1]
    ignore_files = {"__init__.py", "__manifest__.py", "__openerp__.py", "setup.py"}
    warnings = 0

    for root, dirs, files in os.walk(repo_root):
        if "radae" in dirs:
            dirs.remove("radae")
        dirs[:] = [d for d in dirs if d not in ('target', 'venv', '.venv', 'node_modules', 'daemons', 'test_env', '.git')]
        # hams_shared/tools/odoo_type_stubs/ is entirely machine-generated by
        # generate_odoo_core_stubs.py, wiped and rebuilt from scratch on every run (604 files as of
        # 2026-08-27) -- it deliberately mirrors each real core-addon source file's path rather than
        # being organized as a normal importable Odoo module, and mypy's plugin reads these stub
        # files directly by path (not via Python's import machinery), so there is no "forgotten
        # import" for this check to catch here, only noise that would immediately go stale the next
        # time the generator regenerates the tree. Matched by the exact generated path, not just the
        # directory name, so an unrelated directory that happens to be named "odoo_type_stubs"
        # elsewhere in the repo is not silently exempted too.
        rel_parts = os.path.relpath(root, repo_root).split(os.sep)
        if rel_parts[:3] == ["hams_shared", "tools", "odoo_type_stubs"]:
            dirs[:] = []
            continue
        if "__init__.py" in files:
            init_path = os.path.join(root, "__init__.py")
            imported = get_imported_names(init_path)

            for file in files:
                if file.endswith(".py") and file not in ignore_files:
                    rel_path = os.path.relpath(os.path.join(root, file), repo_root)
                    if rel_path in EXCLUDED_FILES:
                        continue
                    mod_name = file[:-3]
                    if mod_name not in imported:
                        print(
                            f"  ❌  ERROR: File '{file}' in '{root}' is never imported in its __init__.py"
                        )
                        warnings += 1

    if warnings > 0:
        print(f"Total Errors (Init Imports): {warnings}")
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
