#!/usr/bin/env python3
# This software is distributed under the terms of the GNU General Public License, version 3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Generates stub files for every real core Odoo addon this codebase depends on
(transitively), so the odoo-aware mypy plugin (odoo_mypy_plugin.py,
ODOO_AWARE_TYPE_CHECKING.md) can resolve a field/method a core addon
contributes -- website_id, get_current_website(), etc. -- the same way it
already resolves this codebase's own _inherit contributors.

Per Bruce's decision (ODOO_AWARE_TYPE_CHECKING.md's "Update, 2026-08-27: ...
build the general stub-generator"): stub every core addon this codebase
needs, generated and regenerated by this script, not hand-maintained file by
file and not narrowed to just the one addon (website) the first false
positives happened to surface.

Confirmed BEFORE writing this generator, not assumed, that the plumbing
already supports core-addon stubs: odoo_mypy_plugin.py's
_fullname_for_contributor already derives real `odoo.addons.<module>...`
fullnames when handed a core_addons_path (its own docstring's "only matches
hams_com/hams_open paths" is now stale -- that was true before Phase 2's
comodel/env[...] work, which needed and added real core-module support). A
one-file hand-written probe stub (website's ResConfigSettings.website_id and
Website.get_current_website) cleared all 9 real false positives on
cloudflare/models/res_config_settings.py with the existing plugin, unmodified
-- so this generator is a mechanical scale-up of a confirmed-working
mechanism, not a plugin change.

Mechanism: reuses odoo_registry_builder.py's own already-tested AST
extraction (_is_model_class, build_registry, FieldInfo/MethodInfo) against
the REAL INSTALLED core addon source (via find_odoo_core_addons_path()),
scoped to exactly the modules find_needed_core_modules() says this codebase
actually needs (the same transitive-closure computation the mypy plugin
itself already uses for _build_real_registry) -- never introspects a live
Odoo registry/database, since AST extraction needs neither and this
codebase's own tooling already trusts it for the identical hams_com/
hams_open-scoped problem.

One stub file per real SOURCE FILE (not one per Odoo model): mirrors each
core addon file's own relative path under odoo_type_stubs/odoo/addons/...,
so odoo_mypy_plugin.py's fullname derivation (dotted module path from file
location) lands on the exact fullname mypy's own import-following expects,
the same way the hand-written probe did.

Deliberately Any-typed throughout, per this file's own generated-file header
comment and the same "don't invent precision" principle odoo_type_stubs'
other hand-written stubs (fields.pyi, api.pyi) already follow: field values,
method args, and return types are all Any. Method arg NAMES and COUNTS are
kept real (from the actual installed source) so a genuinely wrong-arg-count
call still gets flagged -- only the *types* are deliberately unmodeled.

Usage: python3 hams_shared/tools/generate_odoo_core_stubs.py
Regenerate after any Odoo core version upgrade -- this reads the currently
*installed* Odoo package, not a fixed snapshot.
"""

import ast
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import odoo_registry_builder as orb  # noqa: E402

_MODEL_BASE_NAMES = ("Model", "AbstractModel", "TransientModel")
_ast_cache: dict = {}


def _parsed(file_path):
    if file_path not in _ast_cache:
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                _ast_cache[file_path] = ast.parse(f.read(), filename=file_path)
        except (SyntaxError, OSError):
            _ast_cache[file_path] = None
    return _ast_cache[file_path]


def _find_model_base(file_path, class_name):
    """Which of Model/AbstractModel/TransientModel `class_name` in
    `file_path` really extends -- needed so the generated stub inherits
    from odoo_type_stubs' own hand-written BaseModel (models.pyi), the
    same way the real class does. Without this, a generated stub class
    with no declared base loses every framework-level method BaseModel
    provides (search, with_context, with_user, browse, ...), which is
    not addon-specific and was never meant to be re-declared per addon.
    Confirmed as a real, reproduced false-positive class (not theoretical)
    before this function was added: env['ir.model.data'].search(...),
    env['mail.mail'].with_user(...), env['ir.attachment'].with_context(...)
    all false-positived as "has no attribute" once those models got a
    real (base-less) generated stub class for the first time."""
    tree = _parsed(file_path)
    if tree is None:
        return "Model"
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef) or node.name != class_name:
            continue
        for base in node.bases:
            base_name = base.attr if isinstance(base, ast.Attribute) else base.id if isinstance(base, ast.Name) else None
            if base_name in _MODEL_BASE_NAMES:
                return base_name
    return "Model"  # default: real code overwhelmingly extends models.Model

_TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
STUB_ROOT = os.path.join(_TOOLS_DIR, "odoo_type_stubs")
_GENERATED_ADDONS_ROOT = os.path.join(STUB_ROOT, "odoo", "addons")


def _repo_roots():
    """Same resolution odoo_mypy_plugin.py's own _repo_roots() and
    odoo_registry_builder.py's main() use: this file's own location is
    hams_shared/tools/, so hams_com and hams_open are both two directories
    up from there."""
    hams_shared_dir = os.path.dirname(_TOOLS_DIR)
    repo_root = os.path.dirname(hams_shared_dir)
    roots = [repo_root]
    sibling = orb._find_sibling_repo(repo_root)
    if sibling:
        roots.append(sibling)
    return roots


def _stub_path_for(real_file, core_addons_path):
    rel = os.path.relpath(real_file, core_addons_path)
    return os.path.join(_GENERATED_ADDONS_ROOT, rel)


def _render_method_params(method):
    params = []
    n_required = method.posonly_count  # see MethodInfo.min_args's own comment
    for i, arg in enumerate(method.arg_names):
        if i < n_required:
            params.append(f"{arg}: Any")
        else:
            params.append(f"{arg}: Any = ...")
    if method.has_varargs:
        params.append("*args: Any")
    elif method.kwonly_names:
        params.append("*")
    for kw in method.kwonly_names:
        params.append(f"{kw}: Any = ...")
    if method.has_varkw:
        params.append("**kwargs: Any")
    return ", ".join(params)


def _render_stub(real_file, contributions_by_class):
    """contributions_by_class: {class_name: (fields: list[FieldInfo], methods: list[MethodInfo])},
    already deduplicated by name within each class by the caller."""
    lines = [
        "# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.",
        "# Regenerate after any Odoo core version upgrade:",
        "#   python3 hams_shared/tools/generate_odoo_core_stubs.py",
        "#",
        "# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists",
        "# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach",
        "# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method",
        "# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a",
        "# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,",
        "# since inventing precise types here would create a new source of false positives to chase,",
        "# not a real improvement in coverage.",
        "from typing import Any",
        "from odoo import models",
        "",
    ]
    for class_name in sorted(contributions_by_class):
        fields, methods = contributions_by_class[class_name]
        base = _find_model_base(real_file, class_name)
        lines.append(f"class {class_name}(models.{base}):")
        body = []
        seen_fields = set()
        for f in fields:
            if f.name in seen_fields:
                continue
            seen_fields.add(f.name)
            body.append(f"    {f.name}: Any")
        seen_methods = set()
        for m in methods:
            if m.name in seen_methods:
                continue
            seen_methods.add(m.name)
            body.append(f"    def {m.name}({_render_method_params(m)}) -> Any: ...")
        if not body:
            body.append("    pass")
        lines.extend(body)
        lines.append("")
    return "\n".join(lines) + "\n"


def _ensure_package_inits(stub_path):
    d = os.path.dirname(stub_path)
    while d.startswith(_GENERATED_ADDONS_ROOT):
        init_path = os.path.join(d, "__init__.py")
        if not os.path.exists(init_path):
            open(init_path, "w", encoding="utf-8").close()
        if d == _GENERATED_ADDONS_ROOT:
            break
        d = os.path.dirname(d)


def generate():
    hams_roots = _repo_roots()
    core_addons_path = orb.find_odoo_core_addons_path()
    if not core_addons_path:
        print("[!] Odoo core addons not found in this environment -- cannot generate stubs here.")
        return 1

    needed = orb.find_needed_core_modules(hams_roots, core_addons_path)
    print(f"[*] {len(needed)} core Odoo addon(s) needed (transitive closure): {', '.join(sorted(needed))}")

    # This whole subtree is machine-generated -- wipe it before regenerating so a module dropped
    # from the dependency closure, or a class/file removed upstream, doesn't leave a stale stub
    # behind (a stale stub that still resolves is a worse failure mode than a missing one: it
    # would silently hide a real removal instead of surfacing it as a fresh false positive).
    shutil.rmtree(_GENERATED_ADDONS_ROOT, ignore_errors=True)

    roots = [os.path.join(core_addons_path, m) for m in sorted(needed)]
    registry = orb.build_registry(roots)

    # Group by (real source file, class name) -- NOT by merged Odoo model name -- since the stub
    # tree mirrors real files (mypy resolves fullnames by file location), not model identities.
    by_file: dict = {}
    for model in registry.values():
        for contributions in model.field_contributions.values():
            for c in contributions:
                fields, methods = by_file.setdefault(c.file, {}).setdefault(c.class_name, ([], []))
                fields.append(c)
        for contributions in model.method_contributions.values():
            for c in contributions:
                fields, methods = by_file.setdefault(c.file, {}).setdefault(c.class_name, ([], []))
                methods.append(c)

    written = 0
    for real_file, contributions_by_class in sorted(by_file.items()):
        stub_path = _stub_path_for(real_file, core_addons_path)
        os.makedirs(os.path.dirname(stub_path), exist_ok=True)
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(_render_stub(real_file, contributions_by_class))
        _ensure_package_inits(stub_path)
        written += 1

    print(f"[*] Wrote {written} stub file(s) under {_GENERATED_ADDONS_ROOT}")
    return 0


if __name__ == "__main__":
    sys.exit(generate())
