#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""static_site_ctl: provision the read-only static file server that sits beside an Odoo tenant (ADR 0105).

    static_site_ctl.py create  TENANT_SPEC [--apply]                 plan (default) or apply: account, directories,
                                                                    config, server copy, drop-in, unit
    static_site_ctl.py install TENANT_SPEC --source DIR [--apply]    copy the content tree (DIR holds `static/`)
    static_site_ctl.py status  TENANT_SPEC                           unit state and a loopback probe

The tenant spec (tools/tenants/perens_com.json) carries `"static_site": {"port": 18201, "path": "/static/"}`; the
tunnel rule `perens.com ^/static/ -> http://localhost:18201` comes from the same spec (tenant_cloudflare.py), so
the port exists in exactly one place. Everything is a Step with a read-only check, like tenant_lib: a plan prints
what would happen, `--apply` does it, a rerun after a failure resumes. Applying needs root on a host designated
`odoo_tenants`; nothing here runs on a test host.

What the account can see: `/var/lib/hams-static/<name>/` (root-owned, read-only to the service, which has no write
path anywhere), its config and its own copy of the server script. `install` does not copy dotfiles, version
control directories, backups, SQL dumps, keys, logs or PHP: the names the server would refuse to serve anyway.
"""

import argparse
import dataclasses
import hashlib
import json
import os
import shutil
import sys
import urllib.error
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import static_site_server as server  # noqa: E402
import tenant_lib as lib  # noqa: E402

STATIC_USER = "hams_static"
UNIT_TEMPLATE = "hams-static@.service"


@dataclasses.dataclass(frozen=True)
class StaticPaths:
    data_root: str = "/var/lib/hams-static"
    conf_root: str = "/etc/hams-static"
    lib_root: str = "/usr/local/lib/hams-static"
    systemd_dir: str = "/etc/systemd/system"

    def site_dir(self, name):
        return os.path.join(self.data_root, name)

    def conf_file(self, name):
        return os.path.join(self.conf_root, f"{name}.json")

    def server_copy(self):
        return os.path.join(self.lib_root, "static_site_server.py")

    def dropin_dir(self, name):
        return os.path.join(self.systemd_dir, f"hams-static@{name}.service.d")


def load_static_spec(path):
    spec = lib.load_spec(path)
    if not spec.get("static_site"):
        raise lib.SpecError(f"{path}: the tenant spec has no static_site")
    return spec


# [@ANCHOR: static_site_ctl:render_config]
# Verified by [@ANCHOR: test_static_site_ctl:render_config]
def render_config(spec, paths, cache_seconds=server.DEFAULT_CACHE_SECONDS):
    static = spec["static_site"]
    return json.dumps({
        "root": paths.site_dir(spec["name"]), "prefix": static["path"], "port": static["port"],
        "bind": "127.0.0.1", "cache_seconds": cache_seconds,
    }, indent=2, sort_keys=True) + "\n"


def render_dropin(spec):
    return (
        "# Generated by static_site_ctl.py from the tenant spec.\n"
        "[Service]\n"
        f"SocketBindAllow=tcp:{spec['static_site']['port']}\n"
    )


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:  # audit-ignore-path
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


# [@ANCHOR: static_site_ctl:filtered_files]
# Verified by [@ANCHOR: test_static_site_ctl:filtered_files]
def filtered_files(source):
    """(copy, excluded): relative paths under `source/static` to copy, and those left out with the reason."""
    root = os.path.join(source, "static")
    copy, excluded = [], []
    for directory, dirnames, filenames in os.walk(root):
        relative_dir = os.path.relpath(directory, source)
        keep = []
        for name in sorted(dirnames):
            path = os.path.join(directory, name)
            if name.startswith(".") or server.is_denied_name(name):
                excluded.append((os.path.join(relative_dir, name) + "/", "dotfile or secret-looking directory"))
            elif os.path.islink(path):
                excluded.append((os.path.join(relative_dir, name), "symbolic link"))
            else:
                keep.append(name)
        dirnames[:] = keep
        for name in sorted(filenames):
            path = os.path.join(directory, name)
            relative = os.path.join(relative_dir, name)
            if os.path.islink(path):
                excluded.append((relative, "symbolic link"))
            elif name.startswith(".") or server.is_denied_name(name):
                excluded.append((relative, "dotfile, backup, key, log, dump or script name"))
            elif not os.path.isfile(path):
                excluded.append((relative, "not a regular file"))
            else:
                copy.append(relative)
    return copy, excluded


def build_create_steps(spec, paths, system, server_source=None):
    name = spec["name"]
    server_source = server_source or os.path.join(os.path.dirname(os.path.abspath(__file__)), "static_site_server.py")
    steps = []

    def add(key, description, action, done=None):
        steps.append(lib.Step(key, description, action, done))

    add("os_user", f"create system user and group {STATIC_USER} (no login, no home)",
        lambda: system.run(["useradd", "--system", "--user-group", "--no-create-home", "--home-dir", "/nonexistent",
                            "--shell", "/usr/sbin/nologin", STATIC_USER]),
        lambda: system.user_exists(STATIC_USER))
    for key, path in (("dir_data", paths.data_root), ("dir_site", paths.site_dir(name)), ("dir_conf", paths.conf_root),
                      ("dir_lib", paths.lib_root)):
        add(key, f"directory {path} mode 755 owner root:root (the service can read it and cannot write it)",
            lambda p=path: system.makedirs(p, 0o755, "root:root"), lambda p=path: system.exists(p))
    config = render_config(spec, paths)
    add("config", f"write {paths.conf_file(name)} (port {spec['static_site']['port']}, prefix {spec['static_site']['path']})",
        lambda: system.write_text(paths.conf_file(name), config, 0o644, "root:root"),
        lambda: system.read_text(paths.conf_file(name)) == config)
    with open(server_source, "r", encoding="utf-8") as handle:  # audit-ignore-path
        server_text = handle.read()
    add("server_copy", f"install {paths.server_copy()} (a root-owned copy; the unit cannot see /opt/hams)",
        lambda: system.write_text(paths.server_copy(), server_text, 0o644, "root:root"),
        lambda: system.read_text(paths.server_copy()) == server_text)
    dropin = render_dropin(spec)
    dropin_path = os.path.join(paths.dropin_dir(name), "10-spec.conf")
    add("dropin", f"systemd drop-in {dropin_path} (the only port the unit may bind)",
        lambda: (system.makedirs(paths.dropin_dir(name), 0o755, "root:root"),
                 system.write_text(dropin_path, dropin, 0o644, "root:root"), system.run(["systemctl", "daemon-reload"])),
        lambda: system.read_text(dropin_path) == dropin)
    unit = f"hams-static@{name}.service"
    add("unit_started", f"enable and start {unit}",
        lambda: system.run(["systemctl", "enable", "--now", unit]),
        lambda: system.run(["systemctl", "is-active", unit], check=False).stdout.strip() == "active")
    return steps


def build_install_steps(spec, paths, system, source, chown=None):
    """Replaces the served tree with a filtered copy of `source/static`, then writes a checksum list beside it."""
    name = spec["name"]
    target = os.path.join(paths.site_dir(name), "static")
    copy, excluded = filtered_files(source)
    if not copy:
        raise lib.SpecError(f"{source}/static holds no files to serve")
    chown = chown or (lambda path: shutil.chown(path, user="root", group="root"))

    def digest():
        h = hashlib.sha256()
        for relative in copy:
            h.update(relative.encode() + b"\0" + sha256_file(os.path.join(source, relative)).encode() + b"\n")
        return h.hexdigest()

    def current_digest():
        text = system.read_text(os.path.join(paths.site_dir(name), "TREE.sha256"))
        return text.strip() if text else None

    def do_copy():
        staging = target + ".new"
        system.remove_tree(staging)
        for relative in copy:
            src = os.path.join(source, relative)
            dst = os.path.join(staging, os.path.relpath(relative, "static"))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
            os.chmod(dst, 0o644)
        for directory, _dirs, _files in os.walk(staging):
            os.chmod(directory, 0o755)
            chown(directory)
            for filename in _files:
                chown(os.path.join(directory, filename))
        previous = target + ".old"
        system.remove_tree(previous)
        if os.path.exists(target):
            os.replace(target, previous)
        os.replace(staging, target)
        system.remove_tree(previous)
        system.write_text(os.path.join(paths.site_dir(name), "TREE.sha256"), digest() + "\n", 0o644, "root:root")
        lines = [f"{sha256_file(os.path.join(source, r))}  {r}" for r in copy]
        system.write_text(os.path.join(paths.site_dir(name), "MANIFEST.sha256"), "\n".join(lines) + "\n", 0o644, "root:root")

    description = (f"copy {len(copy)} file(s) from {source}/static to {target} (left out: {len(excluded)}; "
                   "root-owned, read-only to the service)")
    return [lib.Step("content", description, do_copy, lambda: current_digest() == digest())], copy, excluded


def probe(port, path="/", host="perens.com"):
    request = urllib.request.Request(f"http://127.0.0.1:{port}{path}",
                                     headers={"Host": host, "User-Agent": "HamsStaticProbe/1.0"})

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):
            return None

    try:
        with urllib.request.build_opener(NoRedirect).open(request, timeout=10) as response:
            return response.status
    except urllib.error.HTTPError as exc:
        return exc.code
    except (urllib.error.URLError, OSError):
        return 0


def require_apply_allowed():
    if os.geteuid() != 0:
        raise SystemExit("--apply needs root (sudo)")
    import infrastructure

    if lib.HOST_CLASS not in infrastructure.host_classes():
        raise SystemExit(f"this host is not designated {lib.HOST_CLASS}: refusing (provision.py --host-class odoo_tenants)")


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("create", "install", "status"):
        p = sub.add_parser(name)
        p.add_argument("spec")
        if name != "status":
            p.add_argument("--apply", action="store_true")
        if name == "install":
            p.add_argument("--source", required=True, help="directory that contains `static/`")
    return parser


def main(argv=None, out=print, system=None, paths=None):
    args = build_parser().parse_args(argv)
    system, paths = system or lib.System(), paths or StaticPaths()
    try:
        spec = load_static_spec(args.spec)
    except (lib.SpecError, OSError, ValueError) as exc:
        out(f"error: {exc}")
        return 2
    name = spec["name"]
    if args.command == "status":
        unit = f"hams-static@{name}.service"
        active = system.run(["systemctl", "is-active", unit], check=False).stdout.strip()
        port, prefix = spec["static_site"]["port"], spec["static_site"]["path"]
        out(f"{unit}: {active}")
        out(f"GET {prefix}: HTTP {probe(port, prefix)} (404 is normal: no index); a file you know: use curl on 127.0.0.1:{port}")
        return 0 if active == "active" else 1
    if getattr(args, "apply", False):
        require_apply_allowed()
    if args.command == "create":
        steps = build_create_steps(spec, paths, system)
    else:
        steps, copy, excluded = build_install_steps(spec, paths, system, args.source)
        for relative, reason in excluded:
            out(f"  not copied: {relative} ({reason})")
    pending = lib.execute(steps, args.apply, out)
    out(f"{pending} step(s) {'applied' if args.apply else 'to do (plan only; add --apply)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
