# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrBinary(models.AbstractModel):
    def _find_record(self: Any, xmlid: Any = ..., res_model: Any = ..., res_id: Any = ..., access_token: Any = ..., field: Any = ...) -> Any: ...
    def _record_to_stream(self: Any, record: Any, field_name: Any) -> Any: ...
    def _get_stream_from(self: Any, record: Any, field_name: Any = ..., filename: Any = ..., filename_field: Any = ..., mimetype: Any = ..., default_mimetype: Any = ...) -> Any: ...
    def _get_image_stream_from(self: Any, record: Any, field_name: Any = ..., filename: Any = ..., filename_field: Any = ..., mimetype: Any = ..., default_mimetype: Any = ..., placeholder: Any = ..., width: Any = ..., height: Any = ..., crop: Any = ..., quality: Any = ...) -> Any: ...
    def _get_placeholder_stream(self: Any, path: Any = ...) -> Any: ...
    def _placeholder(self: Any, path: Any = ...) -> Any: ...

