# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrEmbeddedActions(models.Model):
    name: Any
    sequence: Any
    parent_action_id: Any
    parent_res_id: Any
    parent_res_model: Any
    action_id: Any
    python_method: Any
    user_id: Any
    is_deletable: Any
    default_view_mode: Any
    filter_ids: Any
    is_visible: Any
    domain: Any
    context: Any
    groups_ids: Any
    def create(self: Any, vals_list: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...
    def _compute_is_deletable(self: Any) -> Any: ...
    def _compute_is_visible(self: Any) -> Any: ...
    def _unlink_if_action_deletable(self: Any) -> Any: ...
    def _get_readable_fields(self: Any) -> Any: ...

