# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class IrFilters(models.Model):
    name: Any
    user_ids: Any
    domain: Any
    context: Any
    sort: Any
    model_id: Any
    is_default: Any
    action_id: Any
    embedded_action_id: Any
    embedded_parent_res_id: Any
    active: Any
    def _list_all_models(self: Any) -> Any: ...
    def copy_data(self: Any, default: Any = ...) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _get_eval_domain(self: Any) -> Any: ...
    def _get_action_domain(self: Any, action_id: Any = ..., embedded_action_id: Any = ..., embedded_parent_res_id: Any = ...) -> Any: ...
    def get_filters(self: Any, model: Any, action_id: Any = ..., embedded_action_id: Any = ..., embedded_parent_res_id: Any = ...) -> Any: ...
    def create_filter(self: Any, vals: Any) -> Any: ...

