# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class BaseEnableProfilingWizard(models.TransientModel):
    duration: Any
    expiration: Any
    def _compute_expiration(self: Any) -> Any: ...
    def submit(self: Any) -> Any: ...

class IrProfile(models.Model):
    create_date: Any
    session: Any
    name: Any
    duration: Any
    cpu_duration: Any
    init_stack_trace: Any
    sql: Any
    sql_count: Any
    traces_async: Any
    traces_sync: Any
    others: Any
    qweb: Any
    entry_count: Any
    speedscope: Any
    speedscope_url: Any
    config_url: Any
    def _gc_profile(self: Any) -> Any: ...
    def _has_memory_traces(self: Any) -> Any: ...
    def _get_memory_data(self: Any) -> Any: ...
    def _compute_config_url(self: Any) -> Any: ...
    def _compute_speedscope(self: Any) -> Any: ...
    def _default_profile_params(self: Any) -> Any: ...
    def _parse_params(self: Any, params: Any) -> Any: ...
    def _generate_speedscope(self: Any, params: Any) -> Any: ...
    def _add_outputs(self: Any, sp: Any, suffix: Any, params: Any) -> Any: ...
    def _compute_speedscope_url(self: Any) -> Any: ...
    def _enabled_until(self: Any) -> Any: ...
    def set_profiling(self: Any, profile: Any = ..., collectors: Any = ..., params: Any = ...) -> Any: ...
    def action_view_speedscope(self: Any) -> Any: ...

