# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ReportPaperformat(models.Model):
    name: Any
    default: Any
    format: Any
    margin_top: Any
    margin_bottom: Any
    margin_left: Any
    margin_right: Any
    page_height: Any
    page_width: Any
    orientation: Any
    header_line: Any
    header_spacing: Any
    disable_shrinking: Any
    dpi: Any
    report_ids: Any
    print_page_width: Any
    print_page_height: Any
    css_margins: Any
    def _check_format_or_page(self: Any) -> Any: ...
    def _compute_print_page_size(self: Any) -> Any: ...

