# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResCountry(models.Model):
    name: Any
    code: Any
    address_format: Any
    address_view_id: Any
    currency_id: Any
    image_url: Any
    phone_code: Any
    country_group_ids: Any
    country_group_codes: Any
    state_ids: Any
    name_position: Any
    vat_label: Any
    state_required: Any
    zip_required: Any
    def name_search(self: Any, name: Any = ..., domain: Any = ..., operator: Any = ..., limit: Any = ...) -> Any: ...
    def _phone_code_for(self: Any, code: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def unlink(self: Any) -> Any: ...
    def get_address_fields(self: Any) -> Any: ...
    def _compute_image_url(self: Any) -> Any: ...
    def _check_address_format(self: Any) -> Any: ...
    def _compute_country_group_codes(self: Any) -> Any: ...

class ResCountryGroup(models.Model):
    name: Any
    code: Any
    country_ids: Any
    def _sanitize_vals(self: Any, vals: Any) -> Any: ...
    def create(self: Any, vals_list: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...

class ResCountryState(models.Model):
    country_id: Any
    name: Any
    code: Any
    def name_search(self: Any, name: Any = ..., domain: Any = ..., operator: Any = ..., limit: Any = ...) -> Any: ...
    def _search_display_name(self: Any, operator: Any, value: Any) -> Any: ...
    def _get_name_search_domain(self: Any, name: Any, operator: Any) -> Any: ...
    def _compute_display_name(self: Any) -> Any: ...

