# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class EventQuestion(models.Model):
    title: Any
    question_type: Any
    active: Any
    event_type_ids: Any
    event_ids: Any
    event_count: Any
    is_default: Any
    is_reusable: Any
    answer_ids: Any
    sequence: Any
    once_per_order: Any
    is_mandatory_answer: Any
    def _compute_event_count(self: Any) -> Any: ...
    def _compute_is_reusable(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...
    def _unlink_except_answered_question(self: Any) -> Any: ...
    def _unlink_except_default_question(self: Any) -> Any: ...
    def action_view_question_answers(self: Any) -> Any: ...
    def action_event_view(self: Any) -> Any: ...

