# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResConfigSettings(models.TransientModel):
    google_maps_static_api_key: Any
    google_maps_static_api_secret: Any
    module_event_sale: Any
    module_pos_event: Any
    module_website_event_track: Any
    module_website_event_track_live: Any
    module_website_event_track_quiz: Any
    module_website_event_exhibitor: Any
    use_event_barcode: Any
    barcode_nomenclature_id: Any
    module_website_event_sale: Any
    module_event_booth: Any
    use_google_maps_static_api: Any
    def create(self: Any, vals_list: Any) -> Any: ...
    def _default_use_google_maps_static_api(self: Any) -> Any: ...
    def _compute_maps_static_api_key(self: Any) -> Any: ...
    def _compute_maps_static_api_secret(self: Any) -> Any: ...
    def _onchange_module_website_event_track(self: Any) -> Any: ...
    def _check_google_maps_static_api_secret(self: Any) -> Any: ...
    def write(self: Any, vals: Any) -> Any: ...

