# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountMergeWizard(models.TransientModel):
    account_ids: Any
    is_group_by_name: Any
    wizard_line_ids: Any
    disable_merge_button: Any
    def default_get(self: Any, fields: Any) -> Any: ...
    def _get_grouping_key(self: Any, account: Any) -> Any: ...
    def _compute_wizard_line_ids(self: Any) -> Any: ...
    def _compute_disable_merge_button(self: Any) -> Any: ...
    def _get_window_action(self: Any) -> Any: ...
    def action_merge(self: Any) -> Any: ...
    def _check_access_rights(self: Any, accounts: Any) -> Any: ...
    def _action_merge(self: Any, accounts: Any) -> Any: ...

class AccountMergeWizardLine(models.TransientModel):
    wizard_id: Any
    grouping_key: Any
    sequence: Any
    display_type: Any
    is_selected: Any
    account_id: Any
    company_ids: Any
    info: Any
    account_has_hashed_entries: Any
    def _compute_account_has_hashed_entries(self: Any) -> Any: ...
    def _compute_info(self: Any) -> Any: ...
    def _get_group_name(self: Any) -> Any: ...
    def _apply_different_companies_constraint(self: Any) -> Any: ...
    def _apply_hashed_moves_constraint(self: Any) -> Any: ...

