# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class AccountMoveReversal(models.TransientModel):
    move_ids: Any
    new_move_ids: Any
    date: Any
    reason: Any
    journal_id: Any
    company_id: Any
    available_journal_ids: Any
    country_code: Any
    residual: Any
    currency_id: Any
    move_type: Any
    def _compute_journal_id(self: Any) -> Any: ...
    def _compute_available_journal_ids(self: Any) -> Any: ...
    def _check_journal_type(self: Any) -> Any: ...
    def default_get(self: Any, fields: Any) -> Any: ...
    def _compute_from_moves(self: Any) -> Any: ...
    def _prepare_default_reversal(self: Any, move: Any) -> Any: ...
    def reverse_moves(self: Any, is_modify: Any = ...) -> Any: ...
    def refund_moves(self: Any) -> Any: ...
    def modify_moves(self: Any) -> Any: ...
    def _modify_default_reverse_values(self: Any, origin_move: Any) -> Any: ...

