# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class CrmActivityReport(models.Model):
    date: Any
    lead_create_date: Any
    date_conversion: Any
    date_deadline: Any
    date_closed: Any
    author_id: Any
    user_id: Any
    team_id: Any
    lead_id: Any
    body: Any
    subtype_id: Any
    mail_activity_type_id: Any
    country_id: Any
    company_id: Any
    stage_id: Any
    partner_id: Any
    lead_type: Any
    active: Any
    tag_ids: Any
    won_status: Any
    def _select(self: Any) -> Any: ...
    def _from(self: Any) -> Any: ...
    def _join(self: Any) -> Any: ...
    def _where(self: Any) -> Any: ...
    def init(self: Any) -> Any: ...

