# AUTO-GENERATED by hams_shared/tools/generate_odoo_core_stubs.py -- do not hand-edit.
# Regenerate after any Odoo core version upgrade:
#   python3 hams_shared/tools/generate_odoo_core_stubs.py
#
# Deliberately Any-typed throughout (field values, method args/return) -- this stub exists
# only to give odoo_mypy_plugin.py's MRO-merging mechanism a real class/attribute to attach
# to (see ODOO_AWARE_TYPE_CHECKING.md), not to model core Odoo's actual value types. Method
# arg NAMES and COUNTS are real (extracted from this addon's real installed source), so a
# genuinely wrong-arg-count call is still flagged; arg and return TYPES are Any everywhere,
# since inventing precise types here would create a new source of false positives to chase,
# not a real improvement in coverage.
from typing import Any
from odoo import models

class ResPartner(models.Model):
    channel_ids: Any
    channel_member_ids: Any
    is_in_call: Any
    rtc_session_ids: Any
    def _compute_is_in_call(self: Any) -> Any: ...
    def search_for_channel_invite(self: Any, search_term: Any, channel_id: Any = ..., limit: Any = ...) -> Any: ...
    def _search_for_channel_invite(self: Any, store: Any, search_term: Any, channel_id: Any = ..., limit: Any = ...) -> Any: ...
    def _search_for_channel_invite_to_store(self: Any, store: Any, channel: Any) -> Any: ...
    def get_mention_suggestions_from_channel(self: Any, channel_id: Any, search: Any, limit: Any = ...) -> Any: ...

